espeak-ng/espeak-ng

- dictsource/fr_list
- dictsource/fr_rules
- dictsource/mt_list
- dictsource/mt_rules
- dictsource/tn_list
- dictsource/tn_rules
- dictsource/tt_list
- dictsource/tt_rules
- espeak-data/voices/test/ko
Changed files:
dictsource/mt_list
dictsource/mt_rules
dictsource/tn_list
dictsource/tn_rules
dictsource/tt_list
dictsource/tt_rules
espeak-data/voices/test/ko
> Some language files added/modified to synchronize with other sources

- dictsource/lv_list
- dictsource/lv_rules
- espeak-data/voices/europe/lv
- phsource/intonation
- phsource/ph_latvian
This is still work in progress, but even now overall sound is much more native.
> Improvements for Latvian language

- src/espeak-ng.c
- src/libespeak-ng/compiledata.c
- src/libespeak-ng/compiledict.c
- src/libespeak-ng/compilembrola.c
- src/libespeak-ng/dictionary.c
- src/libespeak-ng/ieee80.c
- src/libespeak-ng/intonation.c
- src/libespeak-ng/klatt.c
- src/libespeak-ng/mbrowrap.c
- src/libespeak-ng/numbers.c
- src/libespeak-ng/phonemelist.c
- src/libespeak-ng/readclause.c
- src/libespeak-ng/setlengths.c
- src/libespeak-ng/speak_lib.c
- src/libespeak-ng/spect.c
- src/libespeak-ng/synth_mbrola.c
- src/libespeak-ng/synthdata.c
- src/libespeak-ng/synthesize.c
- src/libespeak-ng/tr_languages.c
- src/libespeak-ng/translate.c
- src/libespeak-ng/voices.c
- src/libespeak-ng/wave_sada.c
- src/libespeak-ng/wavegen.c
- src/speak-ng.c
Also use size_t instead of int in some places where it make sense
> Declare variables at their first point of use

- phsource/ph_english
- phsource/phonemes
Phoneme descriptions copied from now removed docs/phonemes.* file to phsource/phonemes and phsource/ph_english files
> Updates for phoneme files

- dictsource/fa_rules
these changes have been down for Persian (Farsi) Language voice fa, fa-en-us, fa-latn
these line has been added to fa_rules, .replace section. (line: 26) these new rules help to replace unknown characters with standard Persian UTF8 characters in process .
Line 47: ٫	،
Line 109: ﺾ	ض
Line 116: ﻆ	ظ
Line 141: ﻙ	ک
Line 184: ۆ	ؤ
this rule has been modified to 
fa_rules file, .group ی section, Line 5639: L09L09) یوم (_Sm3	ijom
for improving pronunciation
> new unknown characters that have been replaced with standard Persian UTF8 characters in process . and improving some rules.

- dictsource/it_list
- dictsource/it_listx
- dictsource/it_rules
- phsource/intonation
- phsource/ph_italian
Improved unstressed phoneme a, improved unstressed phoneme o, set length for phoneme i, added exceptions and review it_rules.
This PR contains also change for spanish intonation in tune q6, I will send the last improvements for spanish intonation in another PR.
> It: Improvements tested on june 2016

- dictsource/kg_list
- dictsource/kg_rules
- espeak-data/voices/trk/kg
- phsource/ph_kyrgyz
- phsource/phonemes
I'm adding here some initial work on getting Espeak-NG to work for the Kyrgyz language. It's working now but needs a lot of tweaking and definitions for characters and numbers.
-josh
> Added the initial Kyrgyz language files for dict, phonemes, and voice

- docs/dictionary.md
- src/libespeak-ng/compiledict.c
- src/libespeak-ng/dictionary.c
- src/libespeak-ng/translate.h
Allow to decrease the score in the rule by adding
> Issue espeak-ng/espeak-ng#120

- README.md
- dictsource/lv_list
- dictsource/lv_rules
- docs/dictionary.md
- docs/voices.md
- espeak-data/voices/xaq/lv
- phsource/intonation
- src/libespeak-ng/translate.h
In some rules **<** now is used in postfix part, to decrease their score, some other improvements.
> Latvian language improvements.

- dictsource/it_list
- dictsource/it_listx
- dictsource/it_rules
- phsource/ph_italian
Contains new pronunciation rules and exceptions for Italian ditc source, improvements for final unstressed o.
> IT: added pronunciation rules and exceptions tested on july/august 2016

- dictsource/ky_rules
- espeak-data/voices/trk/ky
- phsource/ph_kyrgyz
Hi there,
I added word-final stress to Kyrgyz words; and changed the vowel /a/. 
-josh
> Additions to Kyrgyz language files 

- .gitignore
- emscripten/README.md
Some minor edits to emscripten/README given the decision not to include `build_js.sh`, and added the JS worker data to the .gitignore since it should never be committed.
> Minor edits to emscripten/README and main .gitignore

- dictsource/it_list
- dictsource/it_listx
- dictsource/it_rules
- phsource/intonation
- phsource/ph_italian
Updates for rules and exceptions, improved italian intonation, statement to use phoneme j between s and o...
> Improvements for italian language: tested on november-december 2016

- dictsource/lv_list
- dictsource/lv_rules
- docs/dictionary.md
- espeak-ng-data/voices/bat/lv
- phsource/ph_latvian
- src/libespeak-ng/voices.c
- src/libespeak-ng/wavegen.c
Reece, can you mark issues related to language rules mark with appropriate tag?
Thanks!
Valdis
> Some improvements for Latvian, code and documentation

- dictsource/mr_list
- dictsource/mr_rules
- phsource/ph_marathi
Hi,
The NVDA/India informal group did lot of improvements in various Indic language in the espeak.
I'm picking their changes  and  raising PR for each language.
Thanks
> Updating Indic/Marathi (inc/mr) files from older effort

- dictsource/ky_list
- dictsource/ky_rules
- phsource/#phonemes#
- phsource/ph_kyrgyz
mostly the ky_list file has been updated
> updates to kyrgyz language

- Makefile.am
- dictsource/mi_list
- dictsource/mi_rules
- espeak-ng-data/lang/poz/mi
- phsource/ph_maori
- phsource/phonemes
I am new to merging into an upstream project, however github says that this can be 'automatically merged' so I am assuming that nothing I have done clashes with anything else that has been done since I forked.
Thanks
Graham
> Added Māori Language - Alpha version

- dictsource/it_list
- dictsource/it_listx
- src/libespeak-ng/tr_languages.c
reduced length to 160 for unstressed syllables
Added some exceptions to the italian dictionaries
> IT: new improvements tested on april 2017

- emscripten/README.md
- emscripten/js/demo.js
- src/ucd-tools/.gitignore
Fix Issue #243 by updating the directions to compile the JS worker with emscripten.
> Fix Issue #243

- dictsource/lv_list
- dictsource/lv_rules
- phsource/ph_latvian
Rule adjustments, updates for specific words, generic support for Russian language
> Latvian language improvements

- dictsource/it_list
- dictsource/it_listx
- dictsource/it_rules
Added rules and exceptions for italian.
Deleted some symbols/characters from it_lists now available in it_emoji
> IT: new improvements (tested on May 2017)

- dictsource/fa_rules
some rules of Persian language were debugged by Shadyar Khodayari.
> debugging some rules

- dictsource/fa_list
existing of few exceptional words made bug.
this file was debugged through editing exceptional words.
> reading Persian was debugged through editing exceptional words.

- dictsource/it_list
- dictsource/it_listx
- dictsource/it_rules
Pronunciation fixes for Italian language.
> IT: new improvements (tested on june/july 2017)

- dictsource/it_list
- dictsource/it_rules
Just added rules and exceptions for some pronominal and irregular verbs.
> IT: updated it_list and it_rules

- dictsource/it_list
- dictsource/it_listx
- dictsource/it_rules
- phsource/ph_italian
- Added rules for pronominal verbs and  exceptions in italian dictionaries.
- Added statements for consonant weakening in ph_italian.
> IT: new improvements tested on october 2017

- dictsource/af_rules
https://groups.io/g/espeak-ng/message/852
> Afrikaans improvements from message of Christo de Klerk

- docs/dictionary.md
And you can close an issue (I don't know our policy about issues created by me and about resolved/fixed tag).
>  Doc: additional info about issue #106

- Makefile.am
- espeak-ng-data/voices/mb/mb-ar1
- phsource/mbrola/ar1
Add ar1 mbrola support
Modify ar2 mbrola support
> Add mbrola support for arabic

- dictsource/fi_list
- src/libespeak-ng/dictionary.c
word stress and numerals improvements as per http://scripta.kotus.fi/visk/sisallys.php?p=13
> fi: word stress improvements

- dictsource/fr_rules
> French rules

- src/libespeak-ng/compiledata.c
- src/libespeak-ng/compiledict.c
- src/libespeak-ng/dictionary.c
- src/libespeak-ng/intonation.c
- src/libespeak-ng/numbers.c
- src/libespeak-ng/phonemelist.c
- src/libespeak-ng/readclause.c
- src/libespeak-ng/setlengths.c
- src/libespeak-ng/speech.c
- src/libespeak-ng/synth_mbrola.c
- src/libespeak-ng/synthdata.c
- src/libespeak-ng/synthesize.c
- src/libespeak-ng/tr_languages.c
- src/libespeak-ng/translate.c
- src/libespeak-ng/translate.h
- src/libespeak-ng/voices.c
Contributes to #8, which I thought was closed but clearly wasn't yet. There's probably still a few conversions missing.
> readability fix: use boolean instead of 0 and 1 for loop control

- dictsource/it_list
- dictsource/it_listx
- dictsource/it_rules
Improvements for the Italian dictionaries,tested on february 2018
> IT: Added rules for pronominal verbs and exceptions.

- src/libespeak-ng/compiledict.c
- src/libespeak-ng/numbers.c
- src/libespeak-ng/phoneme.h
- src/libespeak-ng/phonemelist.c
- src/libespeak-ng/phonemelist.h
- src/libespeak-ng/readclause.c
- src/libespeak-ng/readclause.h
- src/libespeak-ng/spect.c
- src/libespeak-ng/synth_mbrola.c
- src/libespeak-ng/synthdata.c
- src/libespeak-ng/synthdata.h
- src/libespeak-ng/synthesize.c
- src/libespeak-ng/synthesize.h
- src/libespeak-ng/translate.c
- src/libespeak-ng/voice.h
Still removing some unused externs and passing arguments to functions.
> Code cleanup

- dictsource/fa_list
- dictsource/fa_rules
a new update for Persian language contains debugging, optimization rules and some exceptional words.
> update for Persian language

- src/libespeak-ng/speech.c
When notably the audio card is busy, we should report the issue to the
application, but still permit the application to retry submitting text
to synth, and eventually succeed to open it.
This change simply fixes the update of the out_samplerate variable to track
whether audio is open, and if not when text is submitted by the application,
try again to open it.
> Make it possible to restart speech even when audio open failed once

- dictsource/de_list
- dictsource/de_rules
Yet again, some fixes I thought of, and corrections to some of my previous fixes.
> Yet more fixes

- dictsource/it_list
- dictsource/it_listx
- dictsource/it_rules
- phsource/ph_italian
*	Added statement for unstressed i.
*	fixed rules for i when followed by vowel.
*	Added some exceptions.
> IT: improvements tested on may 2018

- src/libespeak-ng/translate.c
> Emoji: skip multi-word replacements.

- src/libespeak-ng/event.c
- src/libespeak-ng/fifo.c
If a thread is cancelled while it holds a mutex, other threads waiting for
the mutex will never be woken, even if destroying the mutex, thus
leading to a deadlock.
Better just make the thread loops have a proper exit case than risking
the tricky semantic of pthread_cancel.
> Avoid using pthread_cancel

- dictsource/shn_list
- dictsource/shn_rules
Added large numbers for Shan language (**shn_lists**)
> Add large number for Shan Language

- dictsource/shn_list
- dictsource/shn_rules
- phsource/ph_shan
- Reorder consonants
- Fix 6 tones
- Remove prefixes **_)**
- Add comments in **ph_shan** for a better understanding.
> Changes for Shan language

- dictsource/shn_rules
* Remove a letter k from vowel
* Update to master
> Fix vowel error in Shan

- dictsource/zh_list
[https://github.com/espeak-ng/espeak-ng/issues/257#issuecomment-535916653](https://github.com/espeak-ng/espeak-ng/issues/257#issuecomment-535916653)
This good old bug has bben there 4 2 years
> Fix pronunciation of numeral 9

- dictsource/shn_rules
> Add rarely used Shan vowels

- dictsource/shn_rules
> Added rules for single consonant, pauses and ဢ (?) (Shan)

- dictsource/en_rules
Hi, this is a mini-PR to handle the name of the author of the LotR (and derivatives : tolkienian, tolkienic, tolkiendil, etc) in english.
> Added pronunciation of the name 'Tolkien' and derivatives

- Makefile.am
- configure.ac
Allows setting the path for ronn and kramdown
> Improved detection and use of ronn and kramdown

- dictsource/ja_list
- dictsource/ja_rules
- src/windows/installer/Product.wxs
> improvement japanese

- src/libespeak-ng/klatt.c
- src/libespeak-ng/klatt.h
- src/libespeak-ng/phoneme.h
- src/libespeak-ng/speech.c
- src/libespeak-ng/synthdata.c
- src/libespeak-ng/synthdata.h
- src/libespeak-ng/synthesize.c
- src/libespeak-ng/synthesize.h
- src/libespeak-ng/wavegen.c
Various code cleanups: change globals to function arguments, combine functions and remove unused code.
Most changes are with the voice output (klatt.c, wavegen.c etc). There might not be enough test cases to detect if an error has been made here.
> Various code cleanups

- src/speechPlayer/include/speechPlayer.h
- src/speechPlayer/src/frame.cpp
- src/speechPlayer/src/frame.h
- src/speechPlayer/src/sample.h
- src/speechPlayer/src/speechPlayer.cpp
- src/speechPlayer/src/speechPlayer.h
- src/speechPlayer/src/speechWaveGenerator.cpp
- src/speechPlayer/src/speechWaveGenerator.h
- src/speechPlayer/src/utils.h
- src/speechPlayer/src/waveGenerator.h
This pull request relicenses the speechPlayer code under GPL version 3, so it can legally be included in espeak-ng.
> Relicense speechPlayer code under GPL version 3.

- .gitignore
- Makefile.am
- docs/dictionary.md
- tests/cmd_options.test
- tests/dictionary.test
This is an attempt to make the tests more systematic. The goal is to eventually have tests for all  documented functionality, and to have the reasoning behind each test documented. However, that's a really boring task so I'll  just commit the beginning of it now and return to it later.
> Tests for dictionary settings and command line options

- dictsource/qdb_list
- dictsource/qdb_rules
Updated `qdb` (the _lang belta_ conlang) with feedback from The Expanse's speech coach.
> qdb - pronunciation improvements

- espeak-ng-data/voices/!v/robosoft
- espeak-ng-data/voices/!v/robosoft2
We are missing Robosoft 1 and 2, so I created them.
> Added Robosoft 1 and 2.

- dictsource/it_list
- dictsource/it_rules
Improvements to rules for irregular/pronominal verbs and exceptions.
> Updates italian source dictionaries

- dictsource/shn_rules
> add 'aWi' into vowels group

- android/jni/Android.mk
When building android app also include speechplayer code.
> Android: Add speechplayer to ndk-build configuration

- dictsource/smj_list
- dictsource/smj_rules
I have now removed unnecessary commented lines from smj_rules and also duplicate lines from smj_list.
> cleaned commented lines to help with debugging

- dictsource/fa_list
- dictsource/fa_rules
…m relevant to punctuations. Underline character added to lines () [] {} «» to resolve the problem.
>  Underline character added to some punctuations

- chromium_extension/AudioStream.js
Avoid converting input data to Float32Array
> Use Uint8Array for input data 's16' format

- espeak-ng-data/voices/!v/Demonic
- espeak-ng-data/voices/!v/Mr serious
- espeak-ng-data/voices/!v/Tweaky
- espeak-ng-data/voices/!v/antonio
- espeak-ng-data/voices/!v/iven
- espeak-ng-data/voices/!v/iven2
- espeak-ng-data/voices/!v/iven3
- espeak-ng-data/voices/!v/john
- espeak-ng-data/voices/!v/norbert
- espeak-ng-data/voices/!v/pablo
- espeak-ng-data/voices/!v/pedro
They are making the files non-ascii for no useful reason
> Drop non-ascii useless nbsp

- docs/languages.md
Should be input in hiragana and katakana, not Arabic alphabet.
> Fixed a note of Japanese input

- src/libespeak-ng/intonation.c
shifting negative integers has an undefined behavior, so we have to
avoid it entirely. Using * 256 and / 256 provides the expected behavior
while being correctly optimized by the compiler.
> Avoid shifting integers

- .github/workflows/ci.yml
Now that all lsan errors are fixed.
Ref #220
> Add lsan CI run

- .github/workflows/ci.yml
Now that all tsan errors are fixed.
Ref #220
> Add tsan CI run

- .github/workflows/ci.yml
Now that it is fixed by
dab5457620af "Fix deleting FrameManagerImpl*"
261954b4bde9 "Fix deleting SpeechWaveGenerator"
> asan: Re-enable new_delete_type_mismatch

- .github/workflows/ci.yml
Now that all memory errors are fixed.
Ref #220
> Add msan CI run

- tests/common
- tests/ssml.test
Otherwise we would miss errors produced on shutdown.
> tests: Check value returned by espeak-ng

- .github/workflows/ci.yml
- Makefile.am
- tests/common
- tests/ssml.test
Now that all errors are fixed.
> Add valgrind CI run

- src/include/compat/endian.h
- src/windows/data.vcxproj
- src/windows/espeak-ng.vcxproj
- src/windows/installer/Product.wxs
- src/windows/libespeak-ng.vcxproj
- src/windows/libespeak-ng.vcxproj.filters
> improvements for windows project

- dictsource/fr_list
- tests/translate.test
> fr: Fix PR replacement

- .github/workflows/ci.yml
- Makefile.am
The tarball produced by make dist was missing a lot of files, so that
building from it would completely fail.
> Fix generated tarball

- android/build.gradle
we should do that on every release.
Issue #1185
> Android: bump versionCode

- dictsource/tr_rules
> Tr: Improve the pronunciations of "î" and "â"

- CHANGELOG.md
Adds "Totontepec Mixe" as a new language to the changelog.
> Update changelog for mto

- dictsource/qya_list
I finished with the Fixing numbers because is missing probably...
> Fix Numbers

- dictsource/nog_list
> Fix numbers for Nogai

- dictsource/en_list
This PR fixes the pronunciation of Kusto, as in [kusto query](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/).
> Fix pronunciation of Kusto

- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- Android: update gradle and AGP
- Android: rase minimal supported sdk
- Android: explicitly set ndk version
> android: dependency update

- dictsource/ru_list
> a little fix in one russian letter

- .gitignore
- src/windows/libespeak-ng.vcxproj
- src/windows/libespeak-ng.vcxproj.filters
fb06936c b52d1f3afd6803 and c4d8976fbc02 broke it.
> fix compilation on windows

- dictsource/en_list
Fix pronunciation of Nanaimo per [Wikipedia](https://en.wikipedia.org/wiki/Nanaimo) and common usage.
> Fix pronunciation of Nanaimo

- dictsource/es_list
- dictsource/es_rules
Fixes #1325, plus fixes the pronunciation of Drive and Reaper.
> Fixes for r letter in spanish (Latinamerica)

- ChangeLog.md
- android/AndroidManifest.xml
- android/src/com/reecedunn/espeak/CheckVoiceData.java
- android/src/com/reecedunn/espeak/DownloadVoiceData.java
- android/src/com/reecedunn/espeak/EspeakApp.java
- android/src/com/reecedunn/espeak/TtsService.java
- android/src/com/reecedunn/espeak/TtsSettingsActivity.java
- android/src/com/reecedunn/espeak/preference/SeekBarPreference.java
- android/src/com/reecedunn/espeak/preference/SpeakPunctuationPreference.java
- android/src/com/reecedunn/espeak/preference/VoiceVariantPreference.java
> Add directBoot support.

- src/include/espeak-ng/espeak_ng.h
- src/libespeak-ng/speech.c
- tests/api.c
Fixes #1387.
Comments are welcome.
> Add ng API to enable phoneme events

- dictsource/ru_list
@valdisvi, I think I need some help, you've been fixing  Russian language before, and maybe you know how some functions and parameters work in espeak-ng. I can explain how it should sound, and you can try to fix it.
> Russian: Correction for the particle же in word-by-word reading

- dictsource/ru_list
fix for или and delete comment about preposition в, because that's how it already works
> Russian update

- src/libespeak-ng/common.c
- src/libespeak-ng/compiledata.c
- src/libespeak-ng/readclause.c
- src/libespeak-ng/soundicon.c
- src/libespeak-ng/ssml.c
- src/libespeak-ng/translate.c
- src/libespeak-ng/translateword.c
Fixes for code smells from cppcheck static code analysis tool.
Also includes some function refactoring.
> Staticanalysis

- src/libespeak-ng/setlengths.c
Unify common parts of two implementations. Split into smaller functions.
> SetSpeed() refactoring

- src/include/espeak-ng/espeak_ng.h
- src/libespeak-ng/compiledata.c
So we can ship data bundle and compile it AOT.
Helps to make #1291
> Allow out-of-tree intonations compilation

- android/src/com/reecedunn/espeak/TtsService.java
Note: this doesn't fix actual problem for some of the older devices.
Unfortunately i don't have devices with os version below than android 7, so am not able to test.
> Add missing compatibility check for older android versions.

- src/libespeak-ng/compiledata.c
> Remove system() call from compiledata.c

- src/libespeak-ng/compiledata.c
When compile from read-only data bundle (shipped within iOS/macOS app), we can't write compile_report file.
The simplest solution is to (almost) silently discard it.
> Allow phoneme compilation without report generation

- dictsource/be_list
- dictsource/be_rules
- docs/languages.md
- tests/language-pronunciation.test
- fix "здж" > "ждж" rule, fix test for it
- add rules for "б г д дз дж з" at the end of words
- added tests for new rules
- add devoiced rules conversion and tests
- languages.md: fix the Belarusian language name
> Belarusian: add new rules, fix old, tests

- espeak-ng-data/voices/!v/Alicia
- espeak-ng-data/voices/!v/f5
> Fix breathw arg count in Alicia and F5 voices

- android/jni/Application.mk
- android/src/com/reecedunn/espeak/DownloadVoiceData.java
- android/src/com/reecedunn/espeak/FileUtils.java
- android/src/com/reecedunn/espeak/TtsService.java
- Android: enable debug logs in debug build type
- Android: enable debug in native lib
- Android: remove hardcoded chmod
> Android: some fixes

- dictsource/be_rules
- tests/language-pronunciation.test
- add voiced-devoiced rules and test
> Belarusian: add voiced-devoiced rules and test [ready to review]

- dictsource/be_rules
- tests/language-pronunciation.test
soft `з, с` if previous syllable is soft
add test for the new rules
> Belarusian: add rules for softening `з, с` / tests [ready to review]

- src/libespeak-ng/wavegen.c
> Flush sonic stream on rate reset

- dictsource/en_list
> fix pronunciation of uefi

- src/libespeak-ng/dictionary.c
- src/libespeak-ng/speech.c
- src/libespeak-ng/synthdata.c
- src/libespeak-ng/synthesize.h
- src/libespeak-ng/tr_languages.c
- src/libespeak-ng/translate.c
- src/libespeak-ng/translate.h
- src/libespeak-ng/translateword.c
- src/libespeak-ng/wavegen.c
Contribute to #68
Reduce count of globals / externs that could be a file-local static variables
> code cleanup: reduce global externs

- src/libespeak-ng/compiledata.c
- src/libespeak-ng/dictionary.c
- src/libespeak-ng/phoneme.h
- src/libespeak-ng/readclause.c
- src/libespeak-ng/readclause.h
- src/libespeak-ng/speech.c
- src/libespeak-ng/ssml.c
- src/libespeak-ng/synth_mbrola.c
- src/libespeak-ng/synthdata.c
- src/libespeak-ng/synthesize.c
- src/libespeak-ng/synthesize.h
- src/libespeak-ng/tr_languages.c
- src/libespeak-ng/translate.h
- src/libespeak-ng/translateword.c
- src/libespeak-ng/voice.h
- src/libespeak-ng/voices.c
- src/libespeak-ng/wavegen.c
Contribute to #68 
Reduce number of externs and static-returns
> code cleanup: next part

- Makefile.am
- src/libespeak-ng/sPlayer.c
- src/libespeak-ng/speech.c
> tests: build with klatt and speechplayer

- dictsource/be_rules
- phsource/ph_belarusian
- fix IPA chars for "s;" and "z;" phonemes
- add bug note about "...i a..." case
> Belarusian: fix IPA chars

- dictsource/be_list
fix single characters transcription for б, ж, й, ў
> Belarusian: fix single characters transcription

- phsource/ph_russian
> Russian: remove else from v#

- src/CMakeLists.txt
- src/libespeak-ng/CMakeLists.txt
- src/libespeak-ng/intonation.c
- src/libespeak-ng/langopts.c
- src/libespeak-ng/readclause.c
- src/libespeak-ng/synth_mbrola.c
- src/libespeak-ng/synthesize.h
- src/libespeak-ng/voices.c
- src/speechPlayer/src/frame.cpp
- src/speechPlayer/src/speechWaveGenerator.cpp
Next bunch of fixes, including unused, non-consts and statics hunting.
Also improves cmake-based installation on MacOS (default data path and rpath).
> code cleanup: next

- dictsource/en_list
Fix pronunciation of [Leschi](https://en.wikipedia.org/wiki/Leschi,_Seattle) ([Wikipedia IPA](https://en.wikipedia.org/wiki/Leschi_(Nisqually))).
> Fix pronunciation of Leschi

- .github/workflows/ci.yml
- .github/workflows/dist.yml
- .github/workflows/windows.yml
- cmake/data.cmake
- tests/common
- tests/language-replace.test
- tests/ssml.test
So we can run tests parallel with cmake, reducing test time and IO overhead
> tests: do not use temp files

- dictsource/en_list
This PR adds more Washington State municipalities. Pronunciations verified from personal experience and additionally by Wikipedia's IPA.
> Fix more Washington State municipalities

- dictsource/hu_list
- dictsource/hu_rules
Hi Boys,
Since between 2010 and 2012 year, when I created original hu_list and hu_rules files, me not have more time to extending this rule set with more new pronounce rules.
I consulted previous with @alex19EP and promise this larger pull request after february 20, but I simple forgot opening this PR after Liblouis 3.29.0 release publication in march 4TH. :-):-)
SO:
* In hu_list file not happened larger changes, I doed only fiwe optimizations. This change I stored a small first commit.
* The hu_rules file contains new or partially modified pronounce rules for example with cs, ccs, ggy, nny, sz, ssz letters, and contains end of hu_rules file a critical need modification with plus and minus simbols handling related, with affects the Android and perhaps iOS versions.
Previous, with oldest …
> Update hungarian rules into dictsource/hu_list, dictsource/hu_rules files

- dictsource/hu_rules
Hi Boys,
I collected estimate 27 new pronounce exceptions, with I added the dictsource/hu_rules file the update_hungarian_rules branch.
My local machine the ./autogen.sh, ./configure, make commands ran successfull.
If possible, please merge this PR anybody the master branch if have a little time. :-):-)
When will be releasing the 1.52 release? Have an estimated publication date?
Attila
> dictsource/hu_rules: added new collected various exceptions

- ChangeLog.md
- Makefile.am
- dictsource/kaa_list
- dictsource/kaa_rules
- espeak-ng-data/lang/trk/kaa
- phsource/ph_karakalpak
- phsource/phonemes
- src/windows/data.vcxproj
- tests/language-phonemes.test
Adding an initial support for [Karakalpak language](https://en.wikipedia.org/wiki/Karakalpak_language)
> kaa: Add initial support for Karakalpak language

- phsource/mbrola/ptbr
Add more consonant combinations to fix gaps in mb-br1 voice
Look #1054
> Mbrola voice fixes

- src/ucd-tools/CMakeLists.txt
https://github.com/espeak-ng/espeak-ng/issues/1972
> Enable PIC to ucd CMakeLists

- src/libespeak-ng/spect.c
> Fix inclusion of <sys/endian.h>

- docs/building.md
> Fix doc to include g++ dependency

- dictsource/hu_rules
Hy Boys,
Previous I closed an another PR with contains the newest hu_rules changes.
I removed the new exceptions the documentation change related comments, hopefully this way Github workflows ran succesfully.
If not, the issue is not related the previous closed pull requests.
Previous five checks are not passed, more details see with unvanted closed pr #1932 
Attila
> dictsource/hu_rules: added newest exceptions

- src/libespeak-ng/translate.c
- tests/translate.test
- **translate: return fix from 9f2ada457**
- **tests: add for https://github.com/espeak-ng/espeak-ng/pull/1743**
> translate fix

- dictsource/ru_list
last russian fix's before release
> Last russian fix

- dictsource/nl_list
Attempt to fix issue #1732 and add more sane symbols.
> Dutch: added spelling of many missing punctuation symbols

- src/libespeak-ng/numbers.c
- src/libespeak-ng/numbers.h
- src/libespeak-ng/translateword.c
Just give up spitting out digits when it's getting so long.
> TranslateNumber: Take care of ph_out end

- phsource/ph_vietnam
- src/libespeak-ng/compiledata.c
- src/libespeak-ng/setlengths.c
- src/libespeak-ng/synthesize.h
Also automatically check against such mistake.
> vi: Fix overflow due to lengthmod

- src/libespeak-ng/translateword.c
IsLetterGroup would watch for that and not spaces.
> addPluralSuffixes: Also add heading \0

- android/res/values-ru/strings.xml
Russian: Fixed the lines <string name="setting_default_pitch"> and <string name="espeak_pitch_range"> to eliminate confusion between pitch and intonation. The corrections are as close as possible to the Russian names of the corresponding parameters in the NVDA program.
> Russian: edited some strings in strings.xml file

- src/libespeak-ng/voices.c
but the user requests it
Ref: #1807
> LoadVoice: Warn when mbrola or klatt was not compiled in

- dictsource/hu_list
- dictsource/hu_rules
Hy boys,
@alex19EP or anybody when have a little time, please merge newest added changes and exceptions with dictsource/hu_list and dictsource/hu_rules files.
dictsource/hu_list file contains some ordinary number related changes, hu_rules file contains newest founded word spokening related exceptions.
If have more opened another languages related pull requests, the merge is not critical important, except if anybody not doing a maintenance release the 1.52 series. :-):-)
If I found future another exceptions, and if this pull request are still opened, I update the feature branch the newest changes related and doing a git rebase.
My local system the build happens right, hopefully Github online workflow runs happens successfull too. :-):-)
Thank you the future merge if anybody have a little …
> dictsource/hu_list, dictsource/hu_rules: Added newest founded exceptions

- src/libespeak-ng/speech.h
> Allow path_max on Linux for file paths

- CMakeLists.txt
> Cleanup: update CMakeLists.txt option text

- nano/README.md
- nano/espeak-list.nanorc
- nano/espeak-rules.nanorc
- vim/README.md
This pull request adds syntax coloring for nano editor.
It may be useful for those who prefer the simplicity of nano over the normal mode of vim.
> Syntax highlighting for nano editor
