- src/libespeak-ng/spect.c
LoadSpectSeq was opening the spectSeq file with fopen, but never closing it  on returns. On Windows at least, this caused a process calling compilePhonemeData to run out of file handles very early on on the compilation of phoneme data.
> Stop leaking file streams in libespeak-ng's LoadSpectSeq function.

- src/libespeak-ng/compiledata.c
…ULL log argument. If so, log is set to stderr.
> Allow compilePhonemeData and compileIntonations to be called with a NULL log argument 

- dictsource/an_rules
- phsource/ph_aragon
Some time ago, we tested some "improvements" to phonemes for Aragonese at eSpeak, but them was unsuccessful, generating a noise on /k/ and /t/ phonemes, this made it so annoying for people using it daily as backend for screen readers (as NVDA, that recently upgraded from eSpeak to eSpeak NG).
In order to make it usable until we solve that, I'm commenting out the lines that override that phonemes from Spanish.
> Commented out some wrong/testing phonemes for Aragonese

- dictsource/gn_list
- dictsource/gn_rules
- espeak-data/voices/sai/gn
- phsource/ph_guarani
- phsource/phonemes
- src/libespeak-ng/tr_languages.c
Thanks a request from a native speaker I started a work for adding and improving the Guarani language:
ISO 639-1  gn
ISO 639-5 sai (South American Indian: Tupian language ).
In the file "src\libespeak-ng\tr_languages.c" I've added the lines 817-822 to set stress vowels, please check and review.
In phsource\phonemes added two lines to include ph_guarani, please check and review.
This P.R. contains also the file needed for adding a new language.
On gn_lists is used the spanish pronunciation for numbers as is commonly used by Guarani speakers in Paraguay and countries around.
We would like to add this language in eSpeak-ng, thanks.
> Guarani Language

- dictsource/fa_list
these changes have been down for Persian (Farsi) Language voice fa, fa-en-us, fa-latn
the bug fixed, this line has been modified to 
fa_list file, Line 200: _)	paRAntezbaste:
for solving "twice speaking right prentice" issue.
these line has been added to fa_rules, .replace section. (line: 26) these new rules help to replace unknown characters to standard Persian UTF8 characters in process .
Line 47: ٫	،
Line 109: ﺾ	ض
Line 116: ﻆ	ظ
Line 141: ﻙ	ک
Line 184: ۆ	ؤ
this rule has been modified to 
fa_rules file, .group ی section, Line 5639: L09L09) یوم (_Sm3	ijom
for improving pronunciation
> Bug fixed about right prentice, a few new unknown characters and several new exceptional words.

- espeak-data/voices/roa/es
- phsource/intonation
- src/libespeak-ng/tr_languages.c
This is a new intonation for Spanish language, mostly for Castilian spanish, we need more feedback for Latin American Spanish.
Also we changed in src/libespeak-ng/tr_language.c the values for lengthen and amplitude for a convenient impact of stressed sillable and nucleus in clauses, (see lines 694-695).
> Spanish intonation.

- dictsource/it_list
- dictsource/it_listx
- dictsource/it_rules
- phsource/ph_italian
- src/libespeak-ng/dictionary.c
- src/libespeak-ng/tr_languages.c
Removed lengthen penultimate stressed vowels from dictionary.c lines 1469-1475. (See #80).
Fixed length stressed vowels in tr_language.c (see #80).
Improved phonemes, new statements for [a] and long close [o].
Added last improvements in italian dict source tested on april-may 2016.
Thanks.
> Italian: removed lengthen penultimate stressed vowels, last improvements for italian dict-source.

- src/libespeak-ng/speech.c
This function should just discard the currently playing audio,
rather than close the audio device.  After all,
we will probably want to synthesize something else later.
> espeak_ng_Cancel(): discard the audio, don't close the device!

- CHANGELOG.md
- README.md
- docs/dictionary.md
- docs/phontab.md
- docs/voices.md
Found using [mwic](http://jwilk.net/software/mwic) and [anorack](https://github.com/jwilk/anorack).
> Fix typos in documentation

- src/libespeak-ng/fifo.c
- src/libespeak-ng/speech.c
This allows process_espeak_command to stop as soon as possible
Using emacspeak server with espeak-ng (still not published) found that audio was only being stoped after a command is processed (i.e. using pcaudiolib).
This fixes the issue.
> Stop audio output before fifo_stop is called

- dictsource/lv_rules
- docs/add_language.md
- docs/dictionary.md
- src/libespeak-ng/dictionary.c
Spelling is checked for regressions with [espeak-ng-spellcheck](/ValdisVitolins/espeak-ng-spellcheck).
> Initial implementation for issue #155

- emscripten/espeakng_glue.cpp
- emscripten/espeakng_glue.idl
- emscripten/js/demo.js
An undocumented behavior of espeak_SetVoiceByName is that it accepts identifier/filename as well as voice name.
This allows us to select the language in a more deterministic way from js and not rely on the properties selector.
> Use espeak_SetVoiceByName in emscripten glue when only name is provided.

- dictsource/es_list
- dictsource/es_rules
Probably there was a mistake o'mine in last commit for Spanish...
I edited es_rules / ".group e" to re-using the phoneme eI, such  as in preview versions.
> ES: minor fix for eI (vdipht) pronunciation

- src/libespeak-ng/translate.c
I tried to make espeak-ng say with comma, but unsuccesfully. This implementation says ` _'aIns tsv'aI` without comma, similarly to consecutive dots in number.
> Fix for issue #69 Speaking '1,,2' in German only says 'eins'.

- .gitignore
- emscripten/Makefile
- emscripten/README.md
- emscripten/demo.html
- emscripten/espeakng_glue.cpp
- emscripten/espeakng_glue.idl
- emscripten/js/demo.js
- emscripten/js/espeakng.js
- emscripten/post.js
Also:
1. added ``a.out`` and ``a.out.js`` (generated by emscripten) to the main ``.gitignore``
2. fixed the default option in ``emscripten/demo.html``, now being ``english``
3. fixed CSS that made the slider bars look ugly in Firefox
4. updated copyright strings in emscripten files to 2017
> Fixed voice default in demo.html and updated to 1.49.1

- dictsource/it_list
- dictsource/it_listx
- dictsource/it_rules
- phsource/intonation
- phsource/ph_italian
- src/libespeak-ng/tr_languages.c
In this PR:
IT: Removed automatic secondari stress #214 
IT: Unstressed final syllable is diminished 
IT: Preserve unstressed monosyllable words and allow secondary stress in multisillable words indicated as unstressed in it_list #214 . 
IT: Reading roman numerals as ordinals #215 
IT: last improvements tested on january 2017.
> Italian: secondary stress, Roman numbers and last updates

- emscripten/Makefile
I added a test to support compilation of JS on macOS alongside on Linux, as detailed in discussion of issue #243 ( https://github.com/espeak-ng/espeak-ng/issues/243#issuecomment-298897646 )
> emscripten/Makefile support for both Linux, macOS

- src/libespeak-ng/tr_languages.c
Added NUM_DFRACTION_4 flag for decimal numbers.
This affect  Catalan, papiamento, Interlingua and spanish languages.
The aragonese is set regardless of.
> Decimal numbers in Spanish

- emscripten/demo.html
- emscripten/espeakng_glue.cpp
- emscripten/espeakng_glue.idl
- emscripten/js/demo.js
- emscripten/js/espeakng.js
- emscripten/post.js
This adds the IPA output feature to the emscripten js library and demo.
It uses the espeak_SetPhonemeTrace to dump the result of espeak_Synth to a temporary virual file in the virtual file system of emscripten and then the content is yielded up to the javascript.
> Adding IPA output to emscripten js library and demo

- espeak-ng-data/lang/sit/cmn
- src/libespeak-ng/tr_languages.c
Reece, please review this commit. `SelectTranslator` is called 2 times for both Chinese dialects,
for first call it loads default settings with `zh` for `yue` and `cmn` and then loads `zhy` if next name says so.
> Fix for issue #338: Chinese Cantonese dictionary (zhy_dict) problem

- src/espeak-ng.c
- src/libespeak-ng/event.c
- src/libespeak-ng/fifo.c
- src/libespeak-ng/phonemelist.c
- src/libespeak-ng/synth_mbrola.c
- src/libespeak-ng/synthdata.c
- src/libespeak-ng/synthesize.c
- src/libespeak-ng/synthesize.h
- src/libespeak-ng/translate.c
- src/libespeak-ng/wavegen.c
See issue #8, https://github.com/espeak-ng/espeak-ng/issues/8
There might still be some ints that could be changed to boolean.
Possible regressions in fifo.c:
int fifo_is_busy() and int fifo_is_command_enabled() used to return an int. Now they return a boolean. This might cause problems on systems where stdbool true/false is something else than 1/0.
> Use stdbool instead of int (Issue #8)

- dictsource/fi_rules
Allative case is recognized by -lle. Enclitics are: -kin, -kaan, -kään, -ko, -kö, -pa, -pä.
This affects words like "meillekö", "kalallekaan" and so on. Also handles multiple enclitics like "koulullekaanko".
There are quite a few cases besides this in finnish where doubling should be done, but they would need part of speech tagging to be recognized. The problem is probably the same for all heavily inflected languages.
> fi: double the initial consonant of enclitics following a word in allative case

- docs/add_language.md
The stray space confuses GitHub’s markdown parser.
> Fix link in documentation

- src/libespeak-ng/readclause.c
Fixes #401.
Before the commit, the ix = end_clause_index was causing the buffer to be cut before the tag, not after it. This made it impossible to have directives at the end of the clause because they were not processed. Notably, returning to default values after a tag was not possible. See discussion of #401 for details.
After the commit, the clause is not cut before the tag and the possible embedded command inside is handled.
Possible regressions:
There are other instances of end_clause_after_tag in the code that do something but I'm unsure what exactly.
> when end_clause_after_tag is set: end clause after the tag, not before the tag

- src/libespeak-ng/event.h
Before this change, the clang compiler produced the following warning:
```
In file included from src/libespeak-ng/espeak_api.c:35:
src/libespeak-ng/event.h:65:28: warning: declaration of 'struct timespec' will
not be visible outside of this function [-Wvisibility]
void clock_gettime2(struct timespec *ts);
^
src/libespeak-ng/event.h:66:28: warning: declaration of 'struct timespec' will
not be visible outside of this function [-Wvisibility]
void add_time_in_ms(struct timespec *ts, int time_in_ms);
^
2 warnings generated.
```
The forward declaration of `struct timespec` makes the warning go away.
> Fix compiler warning

- docs/phonemes.md
- docs/phonemes/cxs.md
- docs/phonemes/kirshenbaum.md
- docs/phonemes/xsampa.md
According to page 5 of [RFC5645](https://tools.ietf.org/html/bcp47#page-1-5),
variant subtags must have 5 to 8 characters. A 9-character subtag is
sytactically ill-formed and should be rejected by conforming parsers.
Technically, BCP47 does not allow the use of unregistered variant subtags.
For `fonkirsh`, I’ve filed a
[language variant subtag registration request](https://mailarchive.ietf.org/arch/msg/ietf-languages/1IrLl3n4wJ4Fr1xXV34QquJn8Bc)
with the IETF. If IETF rejects my request, we could probably add
Kirshenbaum to Unicode’s registry for [RFC6497](https://tools.ietf.org/html/rfc6497).
Not sure what to do about the other non-registered variants. If they’re
commonly used, it might be an option to register them as well, but
they seem to be even more exotic than Kirshenbaum, and we …
> Use correct BCP47 variant subtag for X-Sampa; shorten other variants

- src/libespeak-ng/compiledict.c
- src/libespeak-ng/dictionary.c
- src/libespeak-ng/intonation.c
- src/libespeak-ng/numbers.c
- src/libespeak-ng/numbers.h
- src/libespeak-ng/phoneme.h
- src/libespeak-ng/readclause.c
- src/libespeak-ng/readclause.h
- src/libespeak-ng/setlengths.c
- src/libespeak-ng/setlengths.h
- src/libespeak-ng/spect.c
- src/libespeak-ng/speech.c
- src/libespeak-ng/synth_mbrola.c
- src/libespeak-ng/synthdata.c
- src/libespeak-ng/synthesize.h
- src/libespeak-ng/tr_languages.c
- src/libespeak-ng/translate.c
- src/libespeak-ng/translate.h
- src/libespeak-ng/voices.c
- src/libespeak-ng/wavegen.c
Remove various unused declarations and extern declarations. Move declarations to files and headers they are actually used.
Contributes to cleaner code and #68.
> Code cleanup

- src/espeak-ng.c
Before the change these would segfault:
`espeak-ng --compile`
`espeak-ng --compile <language>`
After the change they print an error message and quit.
This is unchanged and working:
`espeak-ng --compile=<language>`
> Print an error message if voice is not specified with --compile

- Makefile.am
%-style pattern rules are a GNU extension and only used by gnu automake. Suffix rules guarantee portability with non-gnu systems.
Makefile.am already uses suffx rules for documentation (` .md.html` and `.ronn.html`), so this also makes the usage more consistent.
Closes #396.
Further reading:[https://www.gnu.org/software/make/manual/html_node/Suffix-Rules.html]( https://www.gnu.org/software/make/manual/html_node/Suffix-Rules.html) and [https://stackoverflow.com/questions/27975545/how-to-deal-with-autoconf-warning-style-pattern-rules-are-a-gnu-make-extens#27975701](https://stackoverflow.com/questions/27975545/how-to-deal-with-autoconf-warning-style-pattern-rules-are-a-gnu-make-extens#27975701)
> portability: use suffix rules instead of pattern rules.

- Makefile.am
Another try, builds correctly with` ./autogen.sh && make -B`
Closes #343. Also disables installing libfuzzrunner which has been implemented after the issue has been raised.
In addition to the previous PR, this approximately halves the time to run `make` since tests are now build only when running  `make check`.
Further reading: https://www.gnu.org/software/automake/manual/html_node/Libtool-Convenience-Libraries.html
> don't build or install test libraries or programs unnecessarily

- src/libespeak-ng/translate.c
`c = towlower2(c, tr)` is donet here: https://github.com/espeak-ng/espeak-ng/blob/19547ce75b8a865c53ff10e7c16e8b88b227f974/src/libespeak-ng/translate.c#L2287
Setting it again if `UpperCaseInWord` returns 1 is redundant. Thus, checking if `UpperCaseInWord` returns 1 is redundant. Action is only required if it returns 0.
This change only cleans up the code. No change in functionality is intended.
> refactor and remove redundant call to towlower2()

- src/libespeak-ng/tr_languages.c
- src/libespeak-ng/translate.c
- src/libespeak-ng/translate.h
1. refactor setting tone_out in TranslateClause:
Ints tone and tone2 are only used to set tone_out when it's not NULL. It's simpler to set tone_out directly instead. Overriding tone_type in ReadClause seems to only affect Armenian (LANG=hy).
2. remove unused wmark and all related code:
Char  wmark and int word_mark are always 0 so the if clause is never run.
3. remove unused ints testing and phoneme_change:
They are set for Russian (LANG=ru) but there's no code that checks them.
> Refactoring

- src/libespeak-ng/klatt.c
- src/libespeak-ng/wavegen.c
Valgrind reports
==20307== Invalid write of size 1
==20307==    at 0x4E856FE: Wavegen.part.1 (wavegen.c:880)
==20307==    by 0x4E86682: Wavegen (wavegen.c:670)
==20307==    by 0x4E86682: Wavegen2 (wavegen.c:1235)
==20307==    by 0x4E86682: WavegenFill2 (wavegen.c:1317)
==20307==    by 0x4E86CA7: WavegenFill (wavegen.c:1398)
==20307==    by 0x4E7093F: Synthesize (speech.c:442)
==20307==    by 0x4E712E0: sync_espeak_Synth (speech.c:549)
==20307==    by 0x4E8A5C0: process_espeak_command (espeak_command.c:317)
==20307==    by 0x4E8B387: say_thread (fifo.c:333)
==20307==    by 0x50E85A9: start_thread (pthread_create.c:463)
==20307==    by 0x53F5CBE: clone (clone.S:95)
==20307==  Address 0xad5e1bd is 0 bytes after a block of size 2,205 alloc'd
==20307==    at 0x4C2CABF: malloc (in …
> Fix out of bound access when buffer size is odd

- dictsource/de_list
- dictsource/de_rules
Those are more rules for correct pronunciation. The ey rule at end of word was removed to make espeak pronounce names like Meyer, Speyer, etc. correctly which it didn't do before. The other rules I added are also for correct compound word pronunciation. German's got a lot of compound words, a lot of them espeak can't say, but adding every single word there exists would be hard I guess, those are at least a few
> More fixes for German

- dictsource/tr_rules
Related to #500.
Rules for some vowels with circumflex were missing. This commit adds â, ô and û.
Apparently, in turkish circumflex sometimes means lengthening the vowel. It's unclear for which vowels and in what circumstances, so the commit doesn't apply any lengthening to any vowel.
> tr: add pronunciation rules for vowels â, ô, û.

- dictsource/fr_rules
Contributes to #517.
Add letter group L18 to not pronounce the final s in words:
continus, courbatus, discontinus, dodus, imbus, promus, tribus, camus, détritus, rébus
Add letter group L19 to pronounce the final s in words:
clausus, consensus, cursus, typhus, diplodocus, eucalyptus, cirrus
Note that sus is defined in fr_list and is already pronounced correctly when interpreted as a verb ("je sus").
> fr: change pronunciation of some words ending in -us.

- CHANGELOG.md
- Makefile.am
- dictsource/kk_list
- dictsource/kk_rules
- espeak-ng-data/lang/trk/kk
`kk_list` and `kk_rules` files are taken from https://github.com/rhdunn/espeak/issues/125.
> kk: add initial support for Kazakh language

- src/espeak-ng.1.ronn
- src/libespeak-ng/setlengths.c
- src/libespeak-ng/speech.c
- src/libespeak-ng/voices.c
- src/libespeak-ng/wavegen.c
- src/speak-ng.1.ronn
Fix manpage to correct default speed  value 175 words per minute. Fixes #555.
Code cleanup: default speed rate is set by espeakRATE. There are already #defines for the minimum, normal and maximum values. Use them instead of hard coded constans.
> fix manual and clean code related to espeakRATE

- src/espeak-ng.c
- src/include/espeak-ng/espeak_ng.h
- src/include/espeak-ng/speak_lib.h
- src/libespeak-ng/espeak_api.c
- src/libespeak-ng/voices.c
I use espeak/espeak-ng to synthesize vocals for songs. See / listen https://golubovsky.bandcamp.com/album/unhuman-voices
Synthesizing vocals requires voice definitions very different from voices used for speech. Besides, many voice adjustments are needed in the process of song composition, and different voices needed for different parts of a song. Default location of voice files in an installed espeak is under /usr/lib... that is, area not writable by users which makes it very inconvenient to edit voice definition files "ad-hoc". The patch adds flag-option ```--load``` which makes the voice name provided with ```-v``` being treated as path to a file rather than just a voice name.
Thanks.
> Enable loading voice definitions from arbitrary files

- README.md
Literally following the instructions on a base install of Debian results in a build without audio support. This change adds the instruction for installing pcaudiolib development headers, so that the resulting build has audio.
> add line to README to install pcaudiolib on debian

- src/windows/installer/Product.wxs
Fix path for hy-arevmda (replace hy-arevmda with hyw, now windows installer works again).
Per changelog: 
1.49.3 - (In Development)
Add a --disable-rpath option to prevent libtool hardcoding rpaths in the executable.
Renamed the hy-arevmda language to hyw, following the 2018-03-30 change to the BCP 47 language subtag registry making the newly registered hyw language code the preferred value for hy-arevmda. This change keeps support for detecting the hy-arevela and hy-arevmda language tags.
This was not reflected in the windows installer project (Product.wxs) and broke windows build. This pull request fixes that, I was able to compile and install espeak-ng in windows 10 with visual studio 2019 community edition.
> Fix path for hy-arevmda in windows installer

- emscripten/Makefile
- emscripten/js/demo.js
- emscripten/post.js
This is a fix in order to compile the emscripten demo with recent versions of emscripten.
The default behaviour of emscripten is now to compile with WASM option, generating a different data file and forcing async loading. For now, I propose to just stay the closest as possible to what was done before and keep a sync loading by just using WASM=0. 
File System function import in the module has also become an option in emscripten, and we absolutely need it, so the flag should be passed explicitly : FORCE_FILESYSTEM=1
The Runtime functions are now imported directly without scoping the Runtime module: updated accordingly.
That's all for the changes.
> Fix for newer versions of emscripten

- emscripten/js/demo.js
The espeakng.js demo does not currently work on Chrome due to the following [Autoplay policy changes](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes).
> Fix for Chrome Autoplay Policy Changes

- docs/building.md
Current link points to docs/docs/add_language.md (because we are already in docs). Duplicated docs is removed.
> Correct link to add_language.md

- src/libespeak-ng/compiledata.c
This is a fix for (#674). For archiving purpose, the problem was the following : it seems that the `ungetc` implementation under Catalina has interferences with `ftell`/`fseek` when `ungetc` pushes back a character which is different from the one that is preceding the current file pointer.
The fix consists in avoiding such a situation.
> Fixing ungetc bad behavior under macOS Catalina

- emscripten/Makefile
- emscripten/post.js
- src/libespeak-ng/dictionary.c
- src/libespeak-ng/readclause.c
- src/libespeak-ng/readclause.h
- src/libespeak-ng/translate.c
This is a fix for #584, but the PR scope may be potentially larger : without this fix, the handling of compiled rules is not guaranteed to be compliant across platforms, since casting to int* may happen on non aligned char* , which has to be avoided.
Some minor options also have to be added to the emscripten compilation workflow to make it work again with newer versions.
> Rule alignment fixes for non compliant platforms / Fix for emscripten demo

- espeak-ng-data/voices/!v/Andy
- espeak-ng-data/voices/!v/AnxiousAndy
- espeak-ng-data/voices/!v/Lee
- espeak-ng-data/voices/!v/gustave
- espeak-ng-data/voices/!v/linda
- espeak-ng-data/voices/!v/marcelo
The six modified files all had spurious characters introduced apparently
as a result of files with the UTF8 BOM marker, U-FFFE, which is
conventionally used at the start of text files to indicate a UTF-8 file
and is invisible under normal circumstances (e.g. the file is opened as
a text file).
None of these files are recognized by espeak-ng on Linux systems because
the 'language variant' line is seen by espeak-ng as starting with a new
character.
'gustave' is an uncorrupted file, it correctly starts with the BOM in
UTF-8 (three bytes), however even though it is correct espeak-ng does
not read it (this may be a separate bug!)
'marcelo' somehow got the BOM character replaced by a literal '?',
notice that 'git diff' on these changes will, indeed, show the removed
character in 'gustave' as a …
> Fixed UTF8 BOM and consequent damage to !v files

- espeak-ng-data/voices/!v/iven4
This is a smoother version of iven. I personally like it, and I also told about this variant in the german NVDA mailing list. I got one reply from someone being curious about it, so I'll include it in espeak NG. If people don't want to use it, they don't have to. I'm saying all this because I know that I should be careful with changes as it might result in angry users.
> add iven 4 variant

- tests/language-pronunciation.test
- tests/translate.test
With bash, echo "a\nb" will not interpret \n, while with dash, echo will
interpret \n. bash's echo would need -e, but dash does not know that
option and just prints it.
We can however just put \n litteraly in the script, both bash and dash
will understand it.
> Fix testsuite with /bin/sh being bash

- dictsource/en_list
Users of screen readers (eg: Orca, NVDA, JAWS) and other TTS assistive technologies rely on accurate and easy-to-understand reading of the text. One context in which this becomes especially critical is systems administration and software development, where TTS users need to be able to clearly and easily differentiate types of punctuation with minimal effort in the midst of reading a larger portion of text. For example, the two characters have significantly different meanings in shells and in some programming languages.
This PR changes the name of the quote (') character to "tick", as this was difficult to differentiate from """, which reads as "quotes"
> #725: ' (quote) versus " (quotes) is almost impossible to audibly differentiate

- src/espeak-ng.1.ronn
- src/libespeak-ng/mbrowrap.c
- src/libespeak-ng/synth_mbrola.c
- src/libespeak-ng/voices.c
Reece,
please review these changes and merge them if implementation is acceptable.
Thanks!
> Changes in espeak-ng core — improved MBROLA error handling, `all` parameter to list all voices

- src/libespeak-ng/translate.c
- tests/translate.test
@rhdunn, please review and merge fix for #706
I also made it work properly for other languages where, plural/genitive with ...s or ...'s doesn't have meaning (i.e. ..s is considered part of the root word) and updated tests.
> Fix bug #706: pronunciation error with abbreviations followed by 's

- .settings/org.eclipse.jdt.core.prefs
IDE local user files should not be in the project. And it appears to specify Java 1.6 as the JDK to use when loading the project workspace up in Eclipse.
> Remove Eclipse IDE local user specific project settings file.

- src/libespeak-ng/readclause.c
- src/libespeak-ng/translate.c
- tests/translate.test
Hello, this is kind of a bug I've referenced here : #741 .
The handling of the sequence `.'`does not seem totally optimal to me, since a lot of people use the apostrophe character as a simple quote ; espeak considers that this sequence is an acronym followed by a genitive (ex: u.s.a.'s) and thus prevents the last dot from being used as a clause end,  which is annoying in a quoted context : `He said 'I am back.' and left` would trigger the pronunciation of `dot` after `back`.
But this can be easily disambiguated if testing the character after the apostrophe.
> Fixing handling of sequence .' in english

- espeak-ng-data/lang/iro/chr
- phsource/ph_cherokee
Additional improvements to Cherokee. Adjusted the core pitch range to fix an issue with 'g' vs 'd' and increased the pitch range and have the starting and stopping points on the pitch contours much closer to my reference document.
TODO: devoiced vowels
TODO: wh/hw, yh/yh
TODO: Add Eastern Cherokee variant. (s->sh, dZ->tZ, etc.)
> Base pitch range vs tone range adjustments done with Praat analysis.

- src/libespeak-ng/mbrowrap.c
This PR fixes an error with MBROLA support for Windows. You can use MBROLA voices with espeak-ng on Windows by building the DLL from https://github.com/numediart/MBROLA and installing the voices following [the documentation](https://github.com/espeak-ng/espeak-ng/blob/master/docs/mbrola.md)
> Import missing function symbol from DLL in mbrola wrapper

- .gitignore
- Makefile.am
- src/libespeak-ng/speech.c
- tests/mbrola.test
Reece, I couldn't figure out, how to properly test too small buffer from `tests/api.c`, but I created `tests/mbrola.test` for MBROLA voice and checked, that if line is set to `espeak_Initialize(AUDIO_OUTPUT_SYNCHRONOUS, 1, data_path, 0);` in `espeak-ng.c`, test fails.
It may also help in future changes in implementation of eSpeak NG.
> Fix and related test for issue #772

- dictsource/chr_rules
- phsource/ph_cherokee
Switch to Portuguese /&~/ for &lt;v&gt;.
Use aveolar /d/ instead of dental /d[/.
The base phonemes file defines alveolar /d/ with the definition for a
dental /d[/ ????
> Misc Cherokee language fixes.

- dictsource/extra/zh_listx
This item will lead `冉冉` to be pronounced 3 times rather than 2, and
it's not necessary because this character has no overloaded
pronounciation.
Signed-off-by: Icenowy Zheng <icenowy@aosc.io>
> zh_listx: fix bogus `冉冉` item

- dictsource/zh_rules
According to [1] and [2] , the pronounciation of the pinyin character
h is not accurately [x].
According to [2], [χ] is instead a possible pronounication in young
users.
As a young native speaker of Mandarin, I feel the sound of [χ] in espeak
more satisfied than [x] here.
[1] https://en.wikipedia.org/wiki/Standard_Chinese_phonology
[2] https://phesoca.com/aws/268/
Signed-off-by: Icenowy Zheng <icenowy@aosc.io>
> cmn: use voiceless uvular fricative as pronounciation of pinyin h

- src/include/espeak-ng/espeak_ng.h
- src/libespeak-ng/synthesize.c
- src/libespeak-ng/synthesize.h
- src/libespeak-ng/wavegen.c
I've added some hooks to wavegen, which can be used to output aligned speech. This information can be used by prosody transplantation tools similar to MBROLIGN. There is also a function to set a constant f0 in Hz, which may be used by some prosody transplantation tools. If none of the functions is called, the behaviour of espeak-ng is unchanged.
> add output hooks for wavegen

- fastlane/metadata/android/en-US/short_description.txt
- fastlane/metadata/android/es-ES/short_description.txt
I'm sorry I couldn't update this sooner. This is a continuation of PR #820 to list eSpeak NG in F-Droid.
[They recommend](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7136#note_455850781) having short descriptions shorter than 80 characters to prevent F-Droid clients from truncating them, so I'm just doing that with this new commit.
They also recommend [increasing `versionCode`](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7136#note_456343476) in every release, to allow auto-updates. In particular, they ask that the current `versionCode` (20) is larger than the `versionCode` for the [latest tag release](https://github.com/espeak-ng/espeak-ng/releases/tag/1.50).
> Small update for F-Droid

- espeak-ng-data/voices/!v/announcer
It wasn't showing up because their were spaces in the name, so I removed the spaces and it now shows up.
> Fixed announcer variant.

- CHANGELOG.md
- dictsource/jbo_list
- dictsource/jbo_rules
- src/libespeak-ng/readclause.c
- src/libespeak-ng/tr_languages.c
- src/libespeak-ng/translate.c
- src/libespeak-ng/translate.h
- tests/language-pronunciation.test
Multiple lojban pronunciation fixes. The changes in `dictsource/jbo_*` make the lojban specific code in int ReadClause() unnecessary. This is good for code cleanup also.
All diffs come from `xunsku` on #lojban on irc.freenode.org. I only made the PR.
> Lojban pronunciation and code fixes

- src/libespeak-ng/readclause.c
It looks like ssml_ignore_l_angle is just dead code. Can you find any use for it?
It is only set in AnnouncePunctuation if `end_clause != 0`. Even when manually setting ssml_ignore_l_angle there seems to be no effect on anything.
For example, this doesn't change after the commit:
`src/espeak-ng -m --punct "<speak>Here's a &lt; and a &amp;, and < and &. This is still &lt;(&lt;)(&lt;)</speak>"`
If a use case for this is found it should be better documented.
looks like commit 1a2f454af378 from 2008 was first to have ssml_ignore_l_angle in AnnouncePunctuation.
> code cleanup: remove ssml_ignore_l_angle.

- CHANGELOG.md
- docs/numbers.md
- src/libespeak-ng/tr_languages.c
- src/libespeak-ng/translate.h
Can you check my findings and assumptions. This commit will change many languages.
I was instructing someone who is currently adding a new language. They had problems getting numbers working. Nothing in _list was processed. The reason is that number processing is disabled by default. I think it should be on by default so adding a new language is easier. Also see the reasoning in the commit message.
There can be errors if the number definitions are incomplete. The solution would be to fix the number handling code instead of disabling it by default.
I don't speak most of the language affected here. I used a combination of google translate and manually reading the diffs and _list files to figure it out.
If we don't want to change the default behavior we should turn on number processing for …
> Set number handling on by default

- espeak-ng-data/voices/!v/UniRobot
This is quite a mild change, but it was driving me crazy, so I fixed the double "I" in the name of UniversalRobot.
> Fixed a typo in UniversalRobot.

- src/libespeak-ng/voices.c
The only way (in Dec. 2019) to get espeak_ListVoices to actually list
all the voices, including variants and mbrola voices used to be to pass
a non-null voice selector with a null language pointer.  This still
seems to be supported in SetVoiceScores, which still checks for a null
language (see the check right at the top), however new code has been added
for a pseudo voice "all" lower down which seems to do the same thing but
crashes with null.  This change allows "old" code to continue working.
Signed-off-by: John Bowler <jbowler@acm.org>
> Fix crash in voices.c:SetVoiceScores

- Makefile.am
- src/ucd-tools/src/case.c
- tests/ssml-fuzzer.c
cf https://github.com/google/oss-fuzz/pull/5543
- fix a buffer overflow in ucd_tolower leading to failure when
compiling with address sanitizer
- force the use of C++ compiler for espeak-ng
- adding a malloc to have a null-terminated string in the fuzz target
- setting (but not overwriting) ESPEAK_DATA_PATH environment
variable inside the fuzz target
> Oss-fuzz integration

- tests/ssml-fuzzer.c
instead of current working directory
so, the fuzzer can be launched from anywhere
cc @rhdunn @brawer 
This should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34051
and get oss-fuzz running for real
> fuzz: use binary directory for ESPEAK_DATA_PATH

- tests/ssml-fuzzer.c
before overwriting it with a default value for oss-fuzz
cf #939
> fuzzer: test env variable ESPEAK_DATA_PATH

- CHANGELOG.md
- dictsource/cmn_rules
- espeak-ng-data/lang/sit/cmn
- espeak-ng-data/lang/sit/cmn-Latn-pinyin
- espeak-ng-data/lang/sit/yue-Latn-jyutping
NOTE: docs/languages.md still needs updating, but I'm unsure what to write there.
As far as I know there's no reliable way of setting a default fallback language.
This exists: `src/include/espeak-ng/espeak_ng.h:#define ESPEAKNG_DEFAULT_VOICE "en"`
However, English is still hardcoded as default in a few places around the codebase.
There is also `alt_alphabet` and `alt_alphabet_lang` but I don't understand how they work.
> cmn: handle latin characters as English text.

- Makefile.am
- src/libespeak-ng/compiledata.c
- src/libespeak-ng/voices.c
espeak-ng --compile-phonemes generates phontab, but during the
generation it starts by reading the old phontab.  If works just fine,
apart from an error message, if this doesn't exist but if it does exist
it is not clear whether it might end up using old or bad data (e.g.
possibly crashing if phontab is corrupted making it very non-obvious how
to fix the problem...)
The same applies to en_dict as a result of espeak-ng defaulting to the
voice 'en'; again the phontab build works if en_dict is absent but a
spurious message is output.  It's not clear what would happen if someone
tried to build a reduced espeak-ng configuration with just one (non
'en') language.
The fix is to change espeak_ng_CompilePhonemeDataPath to call LoadVoice
with a new flag to indicate the voice structure is just …
> Prevent compile-phonemes use of phontab, en_dict

- dictsource/en_list
This commit adds the usual English pronunciation of my name to the English dictionary.
We could, alternatively, add the native pronunciation, `kS'I2StOf` (or the closest approximation to it I could get out of the English synthesizer), but I'm not sure what the policy on that sort of thing is within the project.
> Add English pronounciation of "Krzysztof" to en_dict

- Makefile.am
- configure.ac
without this fix (assuming it does, what the original author intended to check for), the configure script spits out an error:
checking for ndk-build                                                                              no
checking for gradle                                                                                 no
${_source}/configure: line 13806: 0: command not found
checking if zsp-gcc supports C99 without any flags                                                  yes
checking if zsp-gcc supports C99 with the -std=c99 flag                                             yes
that's because the condition in AM_CONDITIONAL is expected to be a valid shell expression for an if-statement, not just plain value:
{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for gradle" >&5 …
> fix conditional for GRADLE

- Makefile.am
Found with the following script:
```sh
for file in phsource/ph_*; do
grep -qF "$file" Makefile.am || echo "$file missing!";
done
````
I’ve left out one of the files highlighted by that script: `ph_burmese` exists, but isn’t actually used by `phsource/phonemes` (there’s no `include` directive for it).
---
(I noticed these were missing because I went to add `ph_quenya` to the Makefile – pull request for that coming soon :) – and saw that the other `phsource/q*` file also wasn’t listed.)
> Add missing phsource/ files to Makefile.am

- dictsource/he_rules
Adds ךְ and ךָ to Hebrew.
Example use for ךְ and ךָ:
לָךְ (Lakh) means "for you (for females)" while לְךָ (lekha) means "for you (for males)".
> Add ךְ and ךָ

- tests/common
- tests/klatt.test
As ignoring tests is not good and we may get uncaught regressions, I made this workaround for Klatt voice tests.
It allows to set several hash values for different environments and now it works for on my laptop and server for online test site. Klatt4 voice is commented out, as it seems to generate different hash almost all the time. Please merge, if it seems working (probably with more variants of hashes added) for you too.
> Allow several pipe delimited hash values for Klatt tests

- dictsource/en_list
Change several Microsoft-specific terms to their most commonly used pronunciations as heard internally:
* GUID, a [globally unique identifier](https://en.wikipedia.org/wiki/Universally_unique_identifier).
* [winmd](https://docs.microsoft.com/en-gb/uwp/winrt-cref/winmd-files), windows metadata files.
* [UIA](https://en.wikipedia.org/wiki/Microsoft_UI_Automation), an accessibility API and the successer to MSAA (already on the list).
* [XAML](https://en.wikipedia.org/wiki/Extensible_Application_Markup_Language).
> Fix several Microsoft-specific terms

- src/libespeak-ng/compiledict.c
This way we can compile multiple dictionaries at a time without
stepping on 'temp' file from different compilation steps:
$ make -j8 -B
...
make[1]: *** [Makefile:3082: espeak-ng-data/an_dict] Segmentation fault (core dumped)
make[1]: *** Deleting file 'espeak-ng-data/an_dict'
make[1]: *** [Makefile:3082: espeak-ng-data/az_dict] Segmentation fault (core dumped)
make[1]: *** Deleting file 'espeak-ng-data/az_dict'
> compiledict.c: change 'temp' to "${dict}temp" temporary file

- src/libespeak-ng/event.c
event_notify currently introduces an arbitrary 50ms delay between speech
requests. This is usually unnoticed since it's small. But when
cancelling a long series of events, they add up to potentially seconds
of delays, while the user was precisely requesting to just cancel
everything as fast as possible.
This 50ms delay was probably meant to work around some issues elsewhere.
If they are still there, they should be fixed, not worked around.
> event_notify: Remove spurious 50ms delay

- src/include/compat/endian.h
We recently managed to migrate older eSpeak to eSpeak NG on Solaris and this is what we needed to add in order to make it work.
I tested it on both little and big endian (SPARC and Intel CPUs) and everything seems to work.
> Add support for Solaris

- android/eSpeakTests/src/com/reecedunn/espeak/test/VoiceSettingsTest.java
- android/src/com/reecedunn/espeak/SpeechSynthesis.java
this is the maximum espeak-ng's speech rate without using libsonic
> android: limit max speech rate to 449 WPM

- configure.ac
espeak source code uses signed integer wrapping (e.g. wavephase in
wavegen.c's Wavegen). It happens that this is undefined behavior, so a
compiler would be free optimize away various situations... Fortunately gcc
has an -fwrapv option to make signed integer wrapping defined.
Options would be needed for other compilers.
> Pass -fwrapv option to compiler

- src/libespeak-ng/tr_languages.c
valgrind reports
==3632264== Conditional jump or move depends on uninitialised value(s)
==3632264==    at 0x4846688: strcmp (vg_replace_strmem.c:924)
==3632264==    by 0x490EC12: LookupDictList (dictionary.c:2889)
==3632264==    by 0x49554C6: TranslateWord3 (translate.c:588)
==3632264==    by 0x4957FCE: TranslateWord (translate.c:1100)
==3632264==    by 0x4959344: TranslateWord2 (translate.c:1361)
==3632264==    by 0x4961390: TranslateClause (translate.c:2621)
==3632264==    by 0x494FF7A: SpeakNextClause (synthesize.c:1569)
==3632264==    by 0x4939B9D: Synthesize (speech.c:457)
==3632264==    by 0x493AE6A: sync_espeak_Synth (speech.c:570)
==3632264==    by 0x493B286: espeak_ng_Synthesize (speech.c:678)
==3632264==    by 0x4916925: espeak_Synth (espeak_api.c:90)
==3632264==    by 0x10CF5D: …
> Fix uninitialized phonemes_repeat array

- src/libespeak-ng/translate.c
Valgrind reports:
==3642987== Conditional jump or move depends on uninitialised value(s)
==3642987==    at 0x491F268: TranslateNumber_1 (numbers.c:1785)
==3642987==    by 0x4923C35: TranslateNumber (numbers.c:2080)
==3642987==    by 0x49556DC: TranslateWord3 (translate.c:644)
==3642987==    by 0x4957FCE: TranslateWord (translate.c:1100)
==3642987==    by 0x4959344: TranslateWord2 (translate.c:1361)
==3642987==    by 0x496116E: TranslateClause (translate.c:2613)
==3642987==    by 0x494FF7A: SpeakNextClause (synthesize.c:1569)
==3642987==    by 0x4939B9D: Synthesize (speech.c:457)
==3642987==    by 0x493AE6A: sync_espeak_Synth (speech.c:570)
==3642987==    by 0x493B286: espeak_ng_Synthesize (speech.c:678)
==3642987==    by 0x4916925: espeak_Synth (espeak_api.c:90)
==3642987==    by …
> Add more heading margin in TranslateClause

- src/libespeak-ng/compiledata.c
- src/libespeak-ng/spect.c
This avoids having to make LoadEnvelope2 pass &env_x[-1], which is very
strongly frowned upon by sanitizers such as usan.
> Make polint use 0-based indexing

- src/libespeak-ng/dictionary.c
pre_ptr is already one byte before the current letter, so we do not want
to subtract 1 again. Otherwise this would for instance underflow word_iz
of addPluralSuffixes.
> MatchRule: Do not go back before the pre-ptr

- src/libespeak-ng/translate.c
Otherwise asan reports this during make check:
testing en ibm mit ibms mits IBM MIT APH CES ITX IBMs MIT's APHs CES's ITXs
==3733154==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffe420233ef at pc 0x7f2e8a30aef1 bp 0x7ffe42022c80 sp 0x7ffe42022c78
READ of size 1 at 0x7ffe420233ef thread T0
#0 0x7f2e8a30aef0 in utf8_in2 src/libespeak-ng/translate.c:281
#1 0x7f2e8a2a6db1 in MatchRule src/libespeak-ng/dictionary.c:2058
#2 0x7f2e8a2a89e9 in TranslateRules src/libespeak-ng/dictionary.c:2301
#3 0x7f2e8a30cc77 in addPluralSuffixes src/libespeak-ng/translate.c:393
#4 0x7f2e8a30e2c9 in TranslateWord3 src/libespeak-ng/translate.c:684
#5 0x7f2e8a31210b in TranslateWord src/libespeak-ng/translate.c:1100
#6 0x7f2e8a313ef2 in TranslateWord2 src/libespeak-ng/translate.c:1361
#7 …
> addPluralSuffixes: Use space as heading separator

- src/libespeak-ng/dictionary.c
strlen(p) may be arbitrarily long, that would underflow the word, for
instance:
testing fr Latn
=================================================================
==3741805==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffd733c1329 at pc 0x7ff5ffbad2de bp 0x7ffd733bf310 sp 0x7ffd733bf308
READ of size 1 at 0x7ffd733c1329 thread T0
#0 0x7ff5ffbad2dd in IsLetterGroup src/libespeak-ng/dictionary.c:714
#1 0x7ff5ffbbe425 in MatchRule src/libespeak-ng/dictionary.c:1979
#2 0x7ff5ffbc09e9 in TranslateRules src/libespeak-ng/dictionary.c:2301
#3 0x7ff5ffc26656 in TranslateWord3 src/libespeak-ng/translate.c:733
#4 0x7ff5ffc2a10b in TranslateWord src/libespeak-ng/translate.c:1100
#5 0x7ff5ffc2bef2 in TranslateWord2 src/libespeak-ng/translate.c:1361
#6 0x7ff5ffc374e2 in TranslateClause …
> IsLetterGroup: Do not blindly walk back in the word

- src/libespeak-ng/compiledata.c
- src/libespeak-ng/klatt.c
- src/libespeak-ng/klatt.h
- src/libespeak-ng/sPlayer.c
- src/libespeak-ng/sPlayer.h
- src/libespeak-ng/wavegen.c
- src/libespeak-ng/wavegen.h
speechPlayer_terminate was never called without calling
speechPlayer_initialize right after, so there would always be a FrameManager
laying behind.
> Add KlattFiniSP

- src/speechPlayer/src/frame.h
delete playerHandleInfo->frameManager seemingly doesn't actually call
FrameManagerImpl~, probably because playerHandleInfo->frameManager is
only a FrameManager, which doesn't have a destructor, and nothing is
saying that it's actually a FrameManagerImpl behind, and thus FrameManagerImpl~ should be called.
I don't know enough C++ to determine how this is supposed to be fixed
properly.
> Fix deleting FrameManagerImpl*

- src/libespeak-ng/fifo.c
We need to keep the mutex around setting it, to make sure that the
visibility of setting it to true doesn't get delayed, notably not after
the signal (which could entail that the signal becomes useless, leading
to a hang).
> fifo: Protect setting my_terminate_is_required

- src/speechPlayer/src/speechWaveGenerator.h
Similarly to dab5457620af "Fix deleting FrameManagerImpl*", we need a
virtual destructor. clang was complaining about it:
src/speechPlayer/src/speechPlayer.cpp:52:2: warning: delete called on 'SpeechWaveGenerator' that is abstract but has non-virtual destructor [-Wdelete-abstract-non-virtual-dtor]
delete playerHandleInfo->waveGenerator;
^
> Fix deleting SpeechWaveGenerator

- src/libespeak-ng/sPlayer.c
The bw array is 0-based, not 1-based.
> sPlayer: fix accessing bw

- src/libespeak-ng/tr_languages.c
The memory sanitizer would complain:
==4157154==WARNING: MemorySanitizer: use-of-uninitialized-value
#0 0x7fc191d0a85b in TranslateWord3 /home/samy/brl/speech/espeak-ng-git/src/libespeak-ng/translate.c:1065:7
#1 0x7fc191d02916 in TranslateWord /home/samy/brl/speech/espeak-ng-git/src/libespeak-ng/translate.c:1100:14
#2 0x7fc191d1b324 in TranslateWord2 /home/samy/brl/speech/espeak-ng-git/src/libespeak-ng/translate.c:1448:15
#3 0x7fc191d14ebc in TranslateClause /home/samy/brl/speech/espeak-ng-git/src/libespeak-ng/translate.c:2623:17
#4 0x7fc191cfbc9b in SpeakNextClause /home/samy/brl/speech/espeak-ng-git/src/libespeak-ng/synthesize.c:1569:2
#5 0x7fc191cd52fc in Synthesize /home/samy/brl/speech/espeak-ng-git/src/libespeak-ng/speech.c:457:2
#6 0x7fc191cd6d7c in sync_espeak_Synth …
> Fix uninitialized fields

- src/libespeak-ng/voices.c
phonemes_name is only initialized when V_LANGUAGE is met. This is not
necessarily the case, notably with
testing espeak_SetVoiceByName("!v/Annie") (language variant; intonation)
Cannot set intonation: language not set, or is invalid.
Uninitialized bytes in __interceptor_strcmp at offset 0 inside [0x7fff8a875e30, 1)
==4169902==WARNING: MemorySanitizer: use-of-uninitialized-value
#0 0x4c6a49 in LookupPhonemeTable /home/samy/brl/speech/espeak-ng-git/src/libespeak-ng/synthdata.c:363:7
#1 0x4c6a49 in SelectPhonemeTableName /home/samy/brl/speech/espeak-ng-git/src/libespeak-ng/synthdata.c:380:12
#2 0x5098a9 in LoadVoice /home/samy/brl/speech/espeak-ng-git/src/libespeak-ng/voices.c:950:34
#3 0x50edcf in espeak_ng_SetVoiceByName /home/samy/brl/speech/espeak-ng-git/src/libespeak-ng/voices.c:1585:7 …
> LoadVoice: Fix phonemes_name initialization

- src/libespeak-ng/compiledict.c
- src/libespeak-ng/compilembrola.c
- src/libespeak-ng/dictionary.c
Strictly speaking, we are not supposed to use memcmp to compare strings
since we are not supposed to read beyond \0, which memcmp is supposed to
potentially do. Sanitizers would warn about it, and using strncmp happens to
provide the proper semantic while being not really slower, so better
just use them.
> Properly compare strings

- src/libespeak-ng/dictionary.c
LookupDict2 looks forward in the wtab array, it should still stop at its
end. Otherwise the memory sanitizer reports this:
testing en A. B C, D. E: F.
==65960==WARNING: MemorySanitizer: use-of-uninitialized-value
#0 0x7ff9d7ef0de8 in LookupDict2 /home/samy/brl/speech/espeak-ng-git/src/libespeak-ng/dictionary.c:2676:11
#1 0x7ff9d7eec2ec in LookupDictList /home/samy/brl/speech/espeak-ng-git/src/libespeak-ng/dictionary.c:2899:10
#2 0x7ff9d802860a in TranslateWord3 /home/samy/brl/speech/espeak-ng-git/src/libespeak-ng/translate.c:588:12
#3 0x7ff9d80249d4 in TranslateWord /home/samy/brl/speech/espeak-ng-git/src/libespeak-ng/translate.c:1100:14
#4 0x7ff9d8051fe0 in TranslateWord2 /home/samy/brl/speech/espeak-ng-git/src/libespeak-ng/translate.c:1361:11
#5 0x7ff9d804885c in TranslateClause …
> Prevent LookupDict2 from overflowing wtab

- src/libespeak-ng/dictionary.c
Some rules test against character not being of a certain type. That may
match with the \0 beginning-of-text marker, and thus actually step over
it and let MatchRule continue with uninitialized data before it, leading
to potential random behavior.
This commits fixes it by making sure that we don't read before that \0.
> MatchRule: Do not underflow the text

- configure.ac
let's be honest, using espeak-ng without these dictionaries is simply
unbearable... at least for Russian. so let's all get a little bit happy.
> enable all extra dictionaries by default

- src/libespeak-ng/soundicon.c
fname_temp is not always getting filled.
> soundicon: Avoid calling remove with uninitialized name

- src/libespeak-ng/numbers.c
- tests/translate.test
For the case when word is smaller than 4 characters, we should not look at
the 3rd or 4th character before checking the previous ones, otherwise
we'd at best read uninitialized data, at worse non-existing data.
> CheckThousandsGroup: Avoid reading uninitialized data

- configure.ac
- src/libespeak-ng/compiledata.c
- src/libespeak-ng/readclause.c
- src/libespeak-ng/speech.h
- src/libespeak-ng/wavegen.c
These are global arrays reused several times. When using them msan and
valgrind thus believe they are always initialized, which reduces their
capacity to detect uninitialized values. We can however explicitly tell them
when they are reused, and thus to be considered as uninitialized.
> Mark re-used buffers as undefined

- dictsource/es_list
Vilmente is an adverb, so it should be stressed as such.
> Fix stress of "vilmente"

- src/libespeak-ng/voices.c
Fixes #1200 
This reverts commit e91d0a58612a01954687d34c7417cf0fbd3cadaa.
**Problem**
Automatic language switching is now broken for "en" and "fr".
This is because no voice is mapped directly to these language codes.
These normally default to "en-gb" or "fr-fr".
STR, using an installed build of eSpeak 1.51 on Windows, and git bash:
1. Save [bugSample.txt](https://github.com/espeak-ng/espeak-ng/files/8866834/bugSample.txt)
1. Read the text with eSpeak with a German voice: `cat bugSample.txt | "./espeak-ng.exe" -m --stdin -vde`
1. Note that automatic language switching doesn't occur for the second "en" tag
1. Read the text with eSpeak with the default (en-gb) voice: `cat bugSample.txt | "./espeak-ng.exe" -m --stdin`
1. Note that automatic language switching doesn't occur for both "en" tags …
> Revert "code cleanup: don't add a \0 to voices_language in LoadVoice()"

- configure.ac
I propose these further enhancements to the detection of gradle.
Commit messages reproduced for easier reading:
---
**Check more accurately if gradle exists**
Previously, the configure script would only successfully determine that gradle exists if the user specified an absolute path to the executable. It would fail if the user specified only an executable name or if the default value of "gradle" were used. Now it should succeed in either situation.
---
**Remove unnecessary curly braces around var name**
---
**Show in configure summary when gradle is not found**
Previously, if configure determined that gradle could not be found, the summary at the end of the configure output would nevertheless print the name or path of the nonexistent gradle executable that it tried to find. Now it clears …
> Enhance detection of gradle

- dictsource/en_list
This PR adds the correct pronunciation of Issaquah to `en_list`, per [its Wikipedia article](https://en.wikipedia.org/wiki/Issaquah,_Washington).
> Fix pronunciation of Issaquah

- src/libespeak-ng/phonemelist.c
When there are language switches, when we rewind to the start of the
phoneme list we have to reset the phoneme table back.
This avoids some branching that depends on undefined values, caught by
valgrind in the case e.g. of an emoji substitution that contains a
language switch.
Ref #874
> Add missing phoneme table reset

- dictsource/en_list
Fix pronunciation of [puget](https://en.wikipedia.org/wiki/Puget_Sound), [Sammamish](https://en.wikipedia.org/wiki/Sammamish,_Washington), and [Snohomish](https://en.wikipedia.org/wiki/Snohomish_County,_Washington) per Wikipedia.
> Fix pronunciation of Puget, Sammamish, and Snohomish

- dictsource/en_list
Fix pronunciation of schengen, per [Wikipedia](https://en.wikipedia.org/wiki/Schengen_Area) and [YouTube](https://www.youtube.com/watch?v=t7GJHpbto1Y).
> Fix pronunciation of schengen

- espeak-ng-data/voices/!v/Reed
This variant sounds consistent and similar to Reed voice, found on Eloquence. The klatt 6 implementation do not sounds good on small speakers at 22 khz sample rate.
I see that it seems to be very difficult to make the Speech player work at a lower sample rate, like 11025 or 16000hz, because it would require being able to compile the phonemes at such a sample rate.
As many prefer cascade synthesis, this may be the solution.
> Add Reed variant

- docs/dictionary.md
In a few places inside docs/dictionary.md, "character" was written as "charater". This has now been fixed.
> Fixed typo in dictionary documentation.

- espeak-ng-data/voices/mb/mb-fr1-en
- espeak-ng-data/voices/mb/mb-fr4-en
Otherwise if e.g. only mbrola-fr4 is installed, when the application tries
to load voice en-french, it actually ends up trying to load mb-fr1-en.
> mb-fr*-en: Give separate names

- dictsource/en_list
Fix the pronunciation of [Aira](http://aira.io), a popular visual interpretation service for the blind.
> Fix pronunciation of Aira

- Makefile.am
If for whatever reason the build got broken, the recompilation of data
would fail because espeak-ng would be unable to re-open the current
files. One is then stuck until removing the files by hand. Let's make "make
distclean" clear these all to be sure to be able to restart from zero.
> Make distclean-local remove more espeak-ng-data files

- dictsource/en_list
Fix pronunciation of [Kubernetes](https://kubernetes.io/) ([Wikipedia](https://en.wikipedia.org/wiki/Kubernetes), [YouTube](https://www.youtube.com/watch?v=znhnDHAPCZE), [Youtube 2](https://www.youtube.com/watch?v=Dchb_-eEvpg)).
> Fix pronunciation of kubernetes

- dictsource/en_list
This PR fixes the pronunciation of Willamette per [Wikipedia](https://en.wikipedia.org/wiki/Willamette_Valley).
> Fix Willamette

- dictsource/en_list
Follow-up of #1345.
Restrict the new override for "willamette", just in case.
> Add $only to willamette

- src/libespeak-ng/dictionary.c
- tests/language-pronunciation.test
./src/espeak-ng -v ar --path=$PWD 5777
would access out of the vowel_stress array, because GetVowelStress, in the
phcode == phonSYLLABIC case, only increments count if stress is 0.  This
code seems fishy, and is not coherent with the loop in SetWordStress.  I
made it similar to the other case above, thus fixing the out-of-bound
access.
This is modifiying the stress in the tn test, I don't know whether this
is expected.
> Fix out-of-bound vowel_stress access

- .github/workflows/ci.yml
- tests/ssml.test
Following #1368.
Add libsonic to macOS CI builds, re-enable ssml `<prosody>` test.
> Add libsonic to macOS CI build

- dictsource/cmn_list
- dictsource/cmn_rules
- dictsource/extra/cmn_listx
- espeak-ng-data/lang/sit/cmn
- src/libespeak-ng/tr_languages.c
- src/libespeak-ng/translate.c
- tests/translate.test
1. Rewrite cmn_rules. Vowel will be spoken as Mandarin only when it's with a tone number. Otherwise, it will be regarded as English. This will make English words translated more correctly.
2. Fix issue of word item in cmn_listx not taking effect.
3. Fix dictionary_skipwords bug. It should be injected when re-structing method TranslateWord3.
> fix #1370 Cmn voice not correctly translated

- android/build.gradle
- docs/building.md
[This removes the warning that this app may not be compatible because it was developed for an older android-version.](https://developer.android.com/about/versions/10/behavior-changes-all#low-target-sdk-warnings) Also, this adds support for signature scheme v2 and v3 [which reduces the attack surface along with other benefits](https://source.android.com/docs/security/features/apksigning#v1). Lastly this adds 64-bit support for the APK, so this app can be installed on 64-bit-only hardware.
> Increase targetSdk to 30 and support signature scheme v2

- dictsource/ru_rules
words like ножи, персонажи, напиши, покажи.
> Russian: fix for words with ши and жи at end

- dictsource/ru_list
make letter я unstressed at the start of claws, and stressed at end of it
> Russian: fix for letter я

- Makefile.am
wildcard would only work once it's compiled; starting with a pristine tree it would not see them.
> Make sure to test the compiled tests

- .github/workflows/ci.yml
This allows to cover
- another arch that x86, which is also very common
- an arch where char is unsigned
- a little-endian arch
This is running under qemu-user, so significantly slower and doesn't support ptrace thus no address sanitizer etc. but at least the undefined sanitizer works.
> Add arm CI

- src/libespeak-ng/speech.h
On e.g. iOS it may be very long.
Helps to make #1291
> Respect custom N_PATH_HOME definition if passed

- dictsource/be_list
- dictsource/ru_list
- src/libespeak-ng/numbers.c
- src/libespeak-ng/tr_languages.c
I really wonder why the code comment says.
case NUM2_THOUSANDS_VAR2: // lang=cs,sk
and option 4 was used for Czech, and this is not the case when this option fits the language, just the opposite.
it reads 10000000 as 10000, 11000000, as 11000, and so on
almost the same problem was in the Russian language, only it consisted in the fact that the var_1 itself was not made correctly. And here the variant is commented on as the one that is used in the Czech language, but it is not used there. And the worst thing is that everyone does not pay attention to it, well, it reads the wrong number, well, okay.
> Russian and Czech update

- android/jni/jni/eSpeakService.c
There was a problem when reference table was overflowing because of lots of local references.
Now espeak should not crash on some android devices.
> Android: Fixed a crash when trying to get list of voices

- src/libespeak-ng/ssml.c
- src/libespeak-ng/wavegen.c
- tests/ssml.test
Fixes #1512
There was a two bugs.
The first is SSML duration compensation was calculated wrong because rate was not sync to internal global state.
The second causes pauses shorten when sonic compresses it, so I back compensated it in wavegen.
> Fix pause duration for SSML and Sonic

- src/libespeak-ng/ssml.c
Also check for empty skip_marker name in SSML_MARK.
Fixes #975
> Add unquoted attributes support in SSML parser

- dictsource/es_list
In Spanish the letter "r" in the alphabet is correctly pronounced as "ERRe", instead of "Ere".
> Spanish: fix pronunciation of "r" letter

- .github/workflows/ci.yml
- tests/ssml.test
msan requires that we build all code with msan to avoid false positives.
> Disable use of libsonic with msan

- src/libespeak-ng/ssml.c
- src/libespeak-ng/wavegen.c
- tests/ssml.test
Following #1512 
Ref: espeak-ng/espeak-ng-ios-app#34
I unfortunately have broken in-speech pauses by fixing ones that should be constant-time.
This reverts such change and adds a compensation to SSML code.
> Fix non-SSML pauses with libsonic

- src/libespeak-ng/compiledata.c
Contribute to #68
compiledata.c is clean from global state now
```bash
nm -C -l -fbsd src/libespeak-ng/la-compiledata.o | grep -E ' b | B '
```
> code cleanup: localize compiledata static objects

- src/libespeak-ng/compiledict.c
- src/libespeak-ng/compiledict.h
- src/libespeak-ng/dictionary.c
Contribute to #68
compiledict.c is clean from global state now
```bash
nm -C -l -fbsd src/libespeak-ng/la-compiledict.o | grep -E ' b | B '
```
> code cleanup: localize compiledict static objects

- android/jni/jni/eSpeakService.c
ref: #1554
ref for buffer size: https://github.com/nvaccess/nvda/blob/a6fb2392083b5fa1bae926102135ad452746ad3c/source/synthDrivers/_espeak.py#L338
> android: set buffer size to 300

- Makefile.am
- src/espeak-ng.c
- src/include/compat/endian.h
- src/include/compat/getopt.h
- src/include/compat/stdint.h
- src/include/compat/unistd.h
- src/libespeak-ng/espeak_command.c
- src/libespeak-ng/event.c
- src/libespeak-ng/fifo.c
- src/libespeak-ng/klatt.c
- src/libespeak-ng/readclause.c
- src/libespeak-ng/setlengths.c
- src/libespeak-ng/soundicon.c
- src/libespeak-ng/speech.c
- src/libespeak-ng/speech.h
- src/libespeak-ng/ssml.c
- src/libespeak-ng/synth_mbrola.c
- src/libespeak-ng/synthdata.c
- src/libespeak-ng/synthesize.c
- src/libespeak-ng/synthesize.h
- src/libespeak-ng/voices.c
- src/libespeak-ng/wavegen.c
- tests/api.c
Fixes: #1549
A bunch of `#ifdef` stuff cleanups, including:
- Check header presence with `__has_include` instead of autoconf's `HAVE_XXX` macro
- Standartization of defines: consistent naming, define to 1 and check with `#if` instead of `#ifdef`
- Compile MBROLA-related code only if configured `--with-mbrola`
- Compile tests with flags that match configuration (including async, klatt, speechplayer, mbrola)
- Fix for API test when compiled with async
> code cleanup: compilation options

- src/espeak-ng.c
- src/include/espeak-ng/speak_lib.h
- src/libespeak-ng/CMakeLists.txt
- src/libespeak-ng/setlengths.c
- src/libespeak-ng/speech.c
- src/libespeak-ng/ssml.c
- tests/ssml.test
Upstream implementation for feature request on iOS app: https://github.com/espeak-ng/espeak-ng-ios-app/issues/40
> ssml: support break time multiplier

- src/libespeak-ng/wavegen.c
Fixes #1566 (ref https://github.com/espeak-ng/espeak-ng-ios-app/issues/35)
> wavegen: support higher speech rate in embedded commands

- dictsource/en_list
Fix pronunciation of Puyallup ([Wikipedia](https://en.wikipedia.org/wiki/Puyallup,_Washington), [YouTube](https://www.youtube.com/watch?v=RJySijoV5rI)).
> Fix pronunciation of Puyallup

- .github/workflows/autoconf.yml
- .github/workflows/ci.yml
- .github/workflows/dist.yml
OK, now CI is green again. It is github-CI related issue, I think.
The root cause is that libgcc-s1:i386 fails to be installed as dependency (for unknown reason), so it is now installed explicitly.
> ci: fix i386

- src/libespeak-ng/translate.c
Reported by @kirill-jjj.
Before:
```
✗ espeak-ng -x -vru кошKa
k'oS(en)'eI(ru)
✗ espeak-ng -x -vru юMoney
'ju(en)w'0ni(ru)
✗ espeak-ng -x -vru ЮMoney                        
'ju(en)w'0ni(ru)
```
After:
```
✗ espeak-ng -x -vru кошKa 
k'oS(en)k'A:(ru)
✗ espeak-ng -x -vru юMoney
'ju(en)m'Vni(ru)
✗ espeak-ng -x -vru ЮMoney
'ju(en)m'Vni(ru)
```
I have not noticed any negative side-effects and tests are still passing.
But I think there should be a more precise testing, because translator code is very complex (and poorly organised, and not documented, and...)
> translate: fix uppercase word split during alphabet change

- dictsource/en_list
Correct pronunciation of the word "banknote" ([Wiktionary](https://en.wiktionary.org/wiki/banknote)).
> Fix pronunciation of banknote

- src/speechPlayer/src/speechWaveGenerator.cpp
As reported in <https://bugs.freebsd.org/271486>, when the C++ standard library provides std::sample, it causes a compile error when compiling `speechWaveGenerator.cpp`:
```
src/speechPlayer/src/speechWaveGenerator.cpp:197:56: error: reference to 'sample' is ambiguous
unsigned int generate(const unsigned int sampleCount, sample* sampleBuf) {
^
src/speechPlayer/src/sample.h:23:3: note: candidate found by name lookup is 'sample'
} sample;
^
/usr/include/c++/v1/__algorithm/sample.h:95:17: note: candidate found by name lookup is 'std::sample'
_SampleIterator sample(_PopulationIterator __first,
^
```
Since `speechWaveGenerator.cpp` puts `using namespace std;` at the top, fix the error by qualifying `sample` with an explicit `::`.
> speechPlayer: fix sample type qualification to avoid ambiguity

- dictsource/en_list
This PR fixes pronunciation of the name "Shea" (pronounced like "Shay").
> Fix pronunciation of name "Shea"

- src/libespeak-ng/dictionary.c
When looking for dotted abbreviations we must limit ourself to the size of the buffer used for translating the abbreviation.
> LookupDictList: Fix out-of-bound access

- dictsource/en_list
This PR fixes the pronunciation of "bateau" in English, per [Wiktionary](https://en.wiktionary.org/wiki/bateau).
> Fix pronunciation of bateau

- src/libespeak-ng/translate.h
Without this function declaration, the build fails on modern C compilers (ISO C99). This affects e.g. builds on Apple Silicon. This fix is also needed in order to compile [rhasspy/piper](https://github.com/rhasspy/piper) on Apple Silicon.
Build error was:
```
/Users/leo/Development/piper/build/p/src/piper_phonemize_external-build/e/src/espeak_ng_external/src/libespeak-ng/speech.c:872:3: error: call to undeclared function 'TranslateClauseWithTerminator'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
TranslateClauseWithTerminator(translator, NULL, NULL, terminator);
^
1 error generated.
```
> Fixed missing function declaration that prevents build on modern C compilers

- dictsource/pl_rules
This PR removes two unnecessary rules in Polish. They both make sense for English (probably someone just copied them from the English file), but make pronunciation of several Polish words incorrect.
> Small fixes for Polish

- Makefile.am
$(srcdir) was missing on includes for src/include/espeak-ng/espeak-ng.h
> fix compiling in build directory

- src/libespeak-ng/dictionary.c
> dictionary: fix typo

- dictsource/pt_list
Add the Portuguese pronunciation for the dollar. Currently it's pronounced "sifR'&U~" as per the rule at https://github.com/espeak-ng/espeak-ng/blob/cb62d93fd7b61d8593b9ae432e6e2a78e3711a77/dictsource/pt_rules#L1312
> pt_list: add dollar

- src/libespeak-ng/translate.c
This function was added to the `translate.h` header in #1811 but the associated function definition was not added to `translate.c`
> Add missing function definition (TranslateClauseWithTerminator)

- phsource/ph_german
Fixes #890 #616 
essentially reverts this commit https://github.com/espeak-ng/espeak-ng/commit/e07002a1c9e517e0d6de8dc49f3192712b860996
> Revert IPA change to question marks

- src/libespeak-ng/translate.c
84e967c0a2ac ("Update translate.c") (sic) dropped the initialization of number_buf, breaking the CI on ubuntu amd64 clang+msan, ubuntu amd64/i386 gcc/clang+valgrind,
While this probably deserves cleaning up, we'd rather not break the CI, to be able to properly track regressions.
> Fix use-of-uninitialized-value

- src/libespeak-ng/synth_mbrola.c
On non-FHS systems like NixOS, there is no `/usr`. Additionally, Nix has immutable packages so mbrola cannot be installed to espeak-ng’s `datadir`. Instead, packages are expected to find data under one of the paths listed in `XDG_DATA_DIRS` environment variable, as defined in the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html#variables).
Fixes: https://github.com/espeak-ng/espeak-ng/issues/1779
> synth_mbrola: Add support for XDG_DATA_DIRS

- src/libespeak-ng/mbrowrap.c
Upstreaming a patch for handling the difference between Linux & Solaris /proc that we've been carrying in the Solaris packages for 2 years now: 
https://github.com/oracle/solaris-userland/blob/master/components/desktop/espeak-ng/patches/03-procfs.patch
This gets rid of the warning message:
```
mbrowrap error: /proc is unaccessible: No such file or directory
```
> mbrola_is_idle: Make /proc checks work with Solaris /proc

- dictsource/en_list
Fix the pronunciation of Kamala, the name of the [vice president of the US](https://en.wikipedia.org/wiki/Kamala_Harris).
> Fix pronunciation of Kamala

- src/libespeak-ng/encoding.c
> Fix the replacement character in the input string

- src/include/espeak-ng/speak_lib.h
When e.g. using mbrola voices, the sample rate may change. When the application plays audio itself, it needs to know it, and espeak_ng_GetSampleRate does not report that.
> espeakEVENT_SAMPLERATE: Do not mark as internal

- src/libespeak-ng/wavegen.c
q[2] and q[3] are of type intptr_t, i.e. typically 64-bit, but MarkerEvent expects 32-bit ints instead, so that the 4 upper bytes are lost in the conversion. In the case of WCMD_MARKER, these four discarded bytes could contain phoneme codes. This case is somewhat rare on little-endian systems, where "upper" means 'last', but usual on big-endian systems, where "upper" means 'first' (we noticed the bug when testing on a s390x processor). The fix works on 64-bit (where all 8 phoneme bytes are in q[2]) as well as on 32-bit (where the 8 phoneme bytes are distributed over q[2] and q[3]).
fixes #1970
> prevent data loss when converting intptr_t to int

- src/espeak-ng.c
`#if PLATFORM_WINDOWS` doesn't work for some reason.
Fix suggested by @beqabeqa473
> Fix new line conversion on windows

- dictsource/cs_emoji
- Uncomment and translate untranslated Czech emojis
> cs: Translate untranslated Czech emojis

- dictsource/de_list
- phsource/mbrola/de6
I did some major improvements to the words balance and garage and a minor improvement to the word behilflich.
This pull request supersedes the pull request https://github.com/espeak-ng/espeak-ng/pull/1875 as my pronunciation of the word garage sounds more natural.
> German: fixed the words balance, behilflich and garage

- configure.ac
Newer clang doesn't support -print-multiarch, and sometimes -print-runtime-dir doesn't actually contain libclang_rt.fuzzer_no_main-*.a
> Fix looking for libclang_rt.fuzzer_no_main-*.a

- src/libespeak-ng/compiledict.c
To get reproducibility, we should not depend on the memory allocator-provided pointer values. We can instead just use the group creation order.
> compiledict: make rgroup_sorter not depend on allocator

- CMakeLists.txt
Add cmake options and fix cross compile. it's not possible to compile data when cross compile because the binaries are compiled into different architecture
> feat: add cmake options for cross compile

- src/libespeak-ng/klatt.c
- tests/klatt.test
klatt should watch for wdata->mix_wavefile_max like others do already.
Probably we should actually be scaling the wave according to speed.wav_factor rather than backwarding by 3/4, but for now let's at least fix the garbage introduced in the klatt case (which was also getting noticed on big-endian archs where the garbage is different).
> klatt: Fix out-of-bound access

- src/libespeak-ng/wavegen.c
libsonic reads/writes in host order while espeak-ng works with little-endian order.
> libsonic: Fix support on big-endian archs

- src/libespeak-ng/translate.c
Functions like IsLetterGroup may backtrack even through spaces, so we need a \0 head terminator
> TranslateClauseWithTerminator: Add \0 head terminator

- src/libespeak-ng/dictionary.c
Othersize the for loop below decrements w before any checking for \0
> IsLetterGroup: Also handle case when *word is already \0

- src/libespeak-ng/dictionary.c
Other rules may have skipped over a head space terminator.
> MatchRule: Also check for \0 in dot backtracking

- src/libespeak-ng/numbers.c
LookupDict2 checks for phoneme length not being larger than N_PHONEME_BYTES, not 40.
> LookupLetter: Fix ph_buf3 buffer

- src/libespeak-ng/numbers.c
Some languages (e.g. ar, tn) have >20 bytes for _8M1
> LookupThousands, LookupNum3: Increase buffer size

- src/libespeak-ng/mbrowrap.c
When we move buf_ptr, we must update the corresponding size.
> mbrola: Fix overflow

- src/espeak-ng.c
This got broken with eaa0c9aa08350ce8a1343aed4c0a87c1cc329b0e ("Fix truncated fgetc return value in main(espeak-ng.c). [Coverity]") which rightfully stopped adding a bogus EOF at the end of the input, which this line was probably dropping just by luck.
Fixes brailcom/speechd#978
> Fix dropping last byte of stdin input

- src/libespeak-ng/translate.c
The memcpy call after the while fills two slots
> TranslateClauseWithTerminator: keep more room in num_wtab

- src/libespeak-ng/translate.c
The pw loop is not supposed to iterate beyond what was produced by the pn loop above, and not beyond pn (as already tested in the for stanza)
Most often numbers are somehow followed by a space some time so checking for space is most often enough, but if there is text without space after this, we start iterating inside pn (which we are not supposed to), and may never stop before overflowing (if the following text doesn't contain space).
> TranslateClauseWithTerminator: fix overflowing number_buf

- src/include/espeak-ng/speak_lib.h
- src/libespeak-ng/speech.c
This variant of espeak_TextToPhonemes also returns the clause terminator for the text. It is used by [piper-phonemize](https://github.com/rhasspy/piper-phonemize/), and rather than submit this themselves they appear happier to maintain their own fork with this added. See some discussion at [#30](https://github.com/rhasspy/piper-phonemize/issues/30).
I would like the Debian version of espeak to have this function available rather than requiring a separate patched variant for a single function. To me the change seems minimal and a logical extension of the interface, so I'm hoping it is acceptable to upstream.
> Add espeak_TextToPhonemesWithTerminator

- src/libespeak-ng/setlengths.c
The threshold value for the activation of Sonic was changed in 065a0e8f03bfac5677e1503a1c5ea0c6093ec023 without an obvious reason.
Related issues: #131, #1461.
> Increase sonic activation threshold

- dictsource/he_list
- src/libespeak-ng/tr_languages.c
1. Set LOPT_APOSTROPHE bit 1 for Hebrew to ensure final apostrophes are treated as part of the word.
This is relevant for words like בָּגָאז׳ or חָגָ׳ג׳, where the apostrophe represents a phonemic element and should not be ignored during tokenization or phoneme conversion.
Replacement rules will change  ׳ (Hebrew GERESH = U+05F3) to ' (standard apostrophe)
2. Fix numbers and letters pronunciations:
mostly mistakes in stress placement
3. Fix numbers reading:
Example for number reading after fix:
23 -> esR,imv,eSal'oS
23.4 -> esR,imv,eSal'oS nekud'a aRb'a?
23.45 -> esR,imv,eSal'oS nekud'a aRba?,imv,eXam'eS
23.456 -> esR,imv,eSal'oS nekud'a aRb'a? Xam'eS S'eS?
4. No secondary stress mark
In Hebrew there are no secondary stresses
> [HEBREW] Multiple changes

- src/CMakeLists.txt
The `espeak-include` INTERFACE library was missing a dependency on the `ucd` library. This could lead to build failures when `espeak-ng` is consumed as a subdirectory in another CMake project.
**Steps to Reproduce:**
1.  Create a `CMakeLists.txt` file in a new project with the following content:
````cmake
// filepath: CMakeLists.txt
cmake_minimum_required(VERSION 3.25 FATAL_ERROR)
project(hello)
add_subdirectory("${CMAKE_SOURCE_DIR}/espeak-ng") # Assuming espeak-ng is a subdirectory
add_executable(${PROJECT_NAME} hello.cpp) # A simple hello.cpp that includes <iostream>
target_link_libraries(${PROJECT_NAME} PRIVATE espeak-ng)
````
2.  Create a simple `hello.cpp` file:
````cpp
// filepath: hello.cpp
#include <iostream>
int main() {
std::cout << "Hello, world!" << std::endl;
return 0;
}
```` …
> fix ucd library link

- src/include/compat/wctype.h
When trying to compile Espeak integration with Android NDK >= 27 an error is thrown stating `udc_toupper` has no matching function:
```error: no matching function for call to 'udc_toupper'```
Since Android NDK 28 is adviced in order add [support for 16 KB page sizes](https://developer.android.com/guide/practices/page-sizes), I want to suggest to remove this old workaround. This will soon become a requirement to publish apps for Android 15 and above. The example project uses NDK 26, but can still be compiled without issues after these changes. Check out the old commit here:
https://github.com/espeak-ng/espeak-ng/commit/e3487d0cf803a5b8202ef170daedf23f82c565cd
> Android: Remove compatibility fallback

- src/libespeak-ng/dictionary.c
We see false positives in run-time checks of truncating casts (`/RTCc` on MSVC). The loss of bits is intentional here and this commit marks it so.
The additional bitmasks are optimized away by every optimizing compiler, but they remove extra bits before the cast to `char` takes place so no implicit data loss occurs.
> Mark Truncating Casts as Intentional

- cmake/deps.cmake
fix espeak-ng shared library build
```
[ 24%] Linking CXX shared library libespeak-ng.so
/usr/bin/ld: ../../CMakeFiles/sonic.dir/_deps/sonic-git-src/sonic.c.o: relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: failed to set dynamic section sizes: bad value
```
> Enable PIC to sonic deps
